// src/lib/content-meta.ts
// GENERATED by scripts/seed-content.mjs — do not edit by hand.
// Metadata only: titles, categories, standfirsts. Body prose and glossary
// definitions live in the database (see supabase/migrations/0004_content_tables.sql)
// and are fetched per-user by src/lib/content.ts.

export interface ArticleMeta { id: string; title: string; category: string; read: string; extract: string; isSample: boolean; evidence: boolean }
export interface GlossaryMeta { term: string; source?: string; related?: string[] }
export interface GuideMeta { id: string; title: string }

export const ARTICLE_META: ArticleMeta[] = [
  {
    "id": "1.1",
    "title": "The board mandate: making AI oversight a directors' duty in practice",
    "category": "Governance",
    "read": "6 min",
    "extract": "AI oversight is no longer a peripheral IT issue. Here is what the 2024 Code actually requires of your board — and the evidence it expects.",
    "isSample": true,
    "evidence": false
  },
  {
    "id": "1.2",
    "title": "Decision rights: who is actually accountable when the AI decides?",
    "category": "Governance",
    "read": "5 min",
    "extract": "A decision is only 'solely automated' if no human is meaningfully involved — and 'meaningful' is now a legal test your org chart has to pass.",
    "isSample": false,
    "evidence": false
  },
  {
    "id": "1.3",
    "title": "Policy architecture: the small set of documents that governs the machines",
    "category": "Governance",
    "read": "5 min",
    "extract": "Most AI policies are either missing or unread. The FRC expects neither — here is the minimum viable architecture.",
    "isSample": false,
    "evidence": false
  },
  {
    "id": "1.4",
    "title": "The AI register: you cannot govern what you have not listed",
    "category": "Governance",
    "read": "5 min",
    "extract": "Embedded AI in procured software is still your AI. The register is where governance begins — and where due diligence now looks first.",
    "isSample": false,
    "evidence": false
  },
  {
    "id": "1.5",
    "title": "Third-party AI: due diligence when you didn't build the model",
    "category": "Governance",
    "read": "6 min",
    "extract": "Liability for a discriminatory or defective AI decision generally lands on the organisation that used it — not the vendor that built it. Buy accordingly.",
    "isSample": false,
    "evidence": false
  },
  {
    "id": "1.6",
    "title": "Horizon scanning: governing against next year's rules, not last year's",
    "category": "Governance",
    "read": "5 min",
    "extract": "The AI Act was 'delayed' — except for the duties that weren't. Organisations that misread the headlines are already exposed. A scanning process is the fix.",
    "isSample": false,
    "evidence": false
  },
  {
    "id": "1.7",
    "title": "Independent assurance: the difference between believing and knowing",
    "category": "Governance",
    "read": "5 min",
    "extract": "The ICO can compel an audit of your AI with an assessment notice. The only question is whether the first independent review is one you commissioned.",
    "isSample": false,
    "evidence": false
  },
  {
    "id": "1.8",
    "title": "The evidence trail: documentation as the board's safe harbour",
    "category": "Governance",
    "read": "5 min",
    "extract": "Fiduciary protection in the AI era is procedural: what the minutes record, the file evidences, and the organisation can produce without a scramble.",
    "isSample": false,
    "evidence": false
  },
  {
    "id": "2.1",
    "title": "Classifying the estate: risk tiers before anything else",
    "category": "Risk",
    "read": "5 min",
    "extract": "Prohibited, high, limited, minimal — every AI system you use sits in one of four tiers, including the ones your software vendors embedded without telling you.",
    "isSample": true,
    "evidence": false
  },
  {
    "id": "2.2",
    "title": "Risk appetite: deciding what you won't let the machines do",
    "category": "Risk",
    "read": "5 min",
    "extract": "Every organisation has AI red lines. Almost none have written them down — which means they don't operationally exist.",
    "isSample": false,
    "evidence": false
  },
  {
    "id": "2.3",
    "title": "DPIAs and FRIAs: the assessments that come before the deployment",
    "category": "Risk",
    "read": "6 min",
    "extract": "The DPIA is not optional paperwork for AI that decides about people — and if you serve the EU public sector, credit or insurance markets, the FRIA is coming for you too.",
    "isSample": false,
    "evidence": false
  },
  {
    "id": "2.4",
    "title": "The deployer's duties: using someone else's AI properly",
    "category": "Risk",
    "read": "5 min",
    "extract": "You didn't build the model — but the instructions, the input data, the monitoring and the logs are still yours. Deployer duty is where most SMEs actually live.",
    "isSample": false,
    "evidence": false
  },
  {
    "id": "2.5",
    "title": "Treating risk: mitigate, transfer, accept — but decide",
    "category": "Risk",
    "read": "4 min",
    "extract": "An AI risk register full of identified-but-untreated risks is a list of admissions. Every entry needs a decision with a name on it.",
    "isSample": false,
    "evidence": false
  },
  {
    "id": "2.6",
    "title": "When the system misbehaves: readiness, suspension, and the reporting clock",
    "category": "Risk",
    "read": "5 min",
    "extract": "Fifteen days. Ten if someone died. Two for critical infrastructure. The AI Act's incident clocks are short — and they start whether or not you were ready.",
    "isSample": false,
    "evidence": false
  },
  {
    "id": "2.7",
    "title": "Lifecycle monitoring: risk didn't stop when procurement ended",
    "category": "Risk",
    "read": "4 min",
    "extract": "The model updated, the use case drifted, the regulation moved — and your risk assessment is still dated the day you bought it.",
    "isSample": false,
    "evidence": false
  },
  {
    "id": "2.8",
    "title": "Proportionate and provable: risk documentation that fits an SME",
    "category": "Risk",
    "read": "4 min",
    "extract": "The regime now says it plainly: simplified documentation for smaller organisations. Proportionality is permission to be lean — not permission to be empty.",
    "isSample": false,
    "evidence": false
  },
  {
    "id": "3.1",
    "title": "Discrimination risk awareness",
    "category": "Ethics & Fairness",
    "read": "1 min",
    "extract": "Whether the organisation knows where its AI could treat people worse because of who they are: each AI use set against the protected characteristics it could affect, with a named owner.",
    "isSample": true,
    "evidence": true
  },
  {
    "id": "3.2",
    "title": "Bias in data",
    "category": "Ethics & Fairness",
    "read": "1 min",
    "extract": "Whether data is examined for inherited unfairness before it informs decisions about people: where it came from, who is missing, and which ordinary-looking fields stand in for protected characteristics.",
    "isSample": false,
    "evidence": true
  },
  {
    "id": "3.3",
    "title": "Bias testing",
    "category": "Ethics & Fairness",
    "read": "1 min",
    "extract": "Whether the organisation checks what its AI does to different groups: outcomes compared across groups, against thresholds set beforehand, recorded, and repeated after launch.",
    "isSample": false,
    "evidence": true
  },
  {
    "id": "3.4",
    "title": "Special-category data controls",
    "category": "Ethics & Fairness",
    "read": "1 min",
    "extract": "Whether the organisation stops sensitive personal data from driving automated decisions about people unless a lawful exception applies, and whether that rule is enforced.",
    "isSample": false,
    "evidence": true
  },
  {
    "id": "3.5",
    "title": "Meaningful human review",
    "category": "Ethics & Fairness",
    "read": "1 min",
    "extract": "Whether the people who review AI-supported decisions can change them: competent to judge the output, authorised to overrule it, and able to see how it was reached.",
    "isSample": false,
    "evidence": true
  },
  {
    "id": "3.6",
    "title": "Ethical review",
    "category": "Ethics & Fairness",
    "read": "1 min",
    "extract": "Whether there is a defined point before deployment where ethical concerns are heard, and where the reviewers can require changes or refuse outright.",
    "isSample": false,
    "evidence": true
  },
  {
    "id": "3.7",
    "title": "Vendor fairness assurance",
    "category": "Ethics & Fairness",
    "read": "1 min",
    "extract": "Whether a supplier's statement that its AI is fair is tested before the organisation relies on it: evidence asked for, read, re-checked, and backed by contract terms that give a right to look.",
    "isSample": false,
    "evidence": true
  },
  {
    "id": "3.8",
    "title": "Remediation and redress",
    "category": "Ethics & Fairness",
    "read": "1 min",
    "extract": "Whether, when AI is found to have treated people unfairly, the organisation corrects the system, re-examines the decisions it influenced and puts the affected people right.",
    "isSample": false,
    "evidence": true
  },
  {
    "id": "4.1",
    "title": "Talking to a machine: the disclosure duty arriving in August",
    "category": "Transparency",
    "read": "5 min",
    "extract": "From 2 August 2026, people interacting with your chatbot must be told it's a chatbot — unless it's obvious. 'Obvious' is doing more work than most deployments can bear.",
    "isSample": true,
    "evidence": false
  },
  {
    "id": "4.2",
    "title": "Marking the synthetic: watermarks, metadata, and the December deadline",
    "category": "Transparency",
    "read": "6 min",
    "extract": "New generative systems must mark their output from August. Legacy systems get until 2 December 2026. Either way, a visible label alone no longer passes.",
    "isSample": false,
    "evidence": false
  },
  {
    "id": "4.3",
    "title": "Explaining this decision to this person",
    "category": "Transparency",
    "read": "5 min",
    "extract": "The ICO's draft guidance is pointed: decision-specific explanation, not boilerplate. If your system can't say why it refused this applicant, it isn't ready to refuse anyone.",
    "isSample": false,
    "evidence": false
  },
  {
    "id": "4.4",
    "title": "The four safeguards: contestability as working machinery",
    "category": "Transparency",
    "read": "5 min",
    "extract": "Inform, hear representations, provide human intervention, allow contest. The DUAA's four rights are operational duties — and 'operational' is the word the regulator will test.",
    "isSample": false,
    "evidence": false
  },
  {
    "id": "4.5",
    "title": "Explainability by design: buy nothing you cannot explain",
    "category": "Transparency",
    "read": "5 min",
    "extract": "The transparency paradox in one line: your legal duties assume reasoning access your vendor never gave you. Fix it in procurement or live with it in production.",
    "isSample": false,
    "evidence": false
  },
  {
    "id": "4.6",
    "title": "The register as window: internal transparency before external",
    "category": "Transparency",
    "read": "4 min",
    "extract": "Before the organisation explains its AI to anyone else, it has to be able to explain it to itself. The register is where external transparency is manufactured.",
    "isSample": false,
    "evidence": false
  },
  {
    "id": "4.7",
    "title": "Telling people: notification when the algorithm decides",
    "category": "Transparency",
    "read": "4 min",
    "extract": "Buried in clause 14.3 of the terms is not 'informed.' The duty to tell people an algorithm decided about them is converging from both London and Brussels.",
    "isSample": false,
    "evidence": false
  },
  {
    "id": "4.8",
    "title": "Saying what's true: AI claims that survive scrutiny",
    "category": "Transparency",
    "read": "5 min",
    "extract": "'AI-powered' in the deck, a spreadsheet and an intern in production. AI-washing is now a named enforcement priority — and your public claims are the easiest audit anyone will ever run.",
    "isSample": false,
    "evidence": false
  },
  {
    "id": "5.1",
    "title": "Scoping the regime: which of your decisions does the DUAA actually catch?",
    "category": "Governance",
    "read": "5 min",
    "extract": "Two tests decide everything: is the decision significant, and is any human involvement meaningful? Get the scoping wrong and every downstream safeguard is built on the wrong map.",
    "isSample": true,
    "evidence": false
  },
  {
    "id": "5.2",
    "title": "Making the safeguards real: from statutory text to working process",
    "category": "Governance",
    "read": "5 min",
    "extract": "The Act names four rights. The ICO's word is 'operational.' The distance between the two is where most organisations currently live.",
    "isSample": false,
    "evidence": false
  },
  {
    "id": "5.3",
    "title": "Lawful basis for the machine: training, inputs, outputs",
    "category": "Governance",
    "read": "5 min",
    "extract": "The DUAA created a new lawful basis — and immediately banned it for automated decisions. Basis analysis for AI is now a three-layer exercise, and blanket 'legitimate interests' fails all three.",
    "isSample": false,
    "evidence": false
  },
  {
    "id": "5.4",
    "title": "The DPIA as working instrument, not doorstop",
    "category": "Governance",
    "read": "5 min",
    "extract": "For automated decisions and large-scale profiling, the DPIA is close to unavoidable. Done at the right moment, it is also the cheapest design review your AI will ever get.",
    "isSample": false,
    "evidence": false
  },
  {
    "id": "5.5",
    "title": "Special-category flows: finding the sensitive data you didn't know was deciding",
    "category": "Governance",
    "read": "5 min",
    "extract": "The rule is strict and the real problem is sight: health, race and biometric signals enter decision pipelines through side doors nobody logged. Discovery is the control.",
    "isSample": false,
    "evidence": false
  },
  {
    "id": "5.6",
    "title": "Feeding the machine: quality and minimisation as deployer disciplines",
    "category": "Governance",
    "read": "4 min",
    "extract": "Relevant, representative, minimal — the three-word standard for what goes into your AI. Most estates fail on the third word first.",
    "isSample": false,
    "evidence": false
  },
  {
    "id": "5.7",
    "title": "Rights under automation: access, erasure and objection where AI is involved",
    "category": "Governance",
    "read": "5 min",
    "extract": "The subject-access request that touches an AI system is where data-rights machinery usually breaks. Build the AI paths before the request arrives, not during it.",
    "isSample": false,
    "evidence": false
  },
  {
    "id": "5.8",
    "title": "The accountability file: one folder per system, no archaeology",
    "category": "Governance",
    "read": "4 min",
    "extract": "Scoping, basis, DPIA, safeguards, decisions — the UK GDPR's accountability principle, applied to AI, resolves to a folder you can produce in an afternoon.",
    "isSample": false,
    "evidence": false
  },
  {
    "id": "6.1",
    "title": "Knowing the adversary: the attacks that only work on AI",
    "category": "Security",
    "read": "5 min",
    "extract": "Poisoned training data, adversarial inputs, injected prompts, models walking out the door. Your cyber programme was built for none of these.",
    "isSample": true,
    "evidence": false
  },
  {
    "id": "6.2",
    "title": "Secure by design, bought by standard: the NCSC bar for AI",
    "category": "Security",
    "read": "5 min",
    "extract": "The UK has published what 'secure AI' means — guidelines, then a code of practice. The only question left is whether your build and procurement actually require it.",
    "isSample": false,
    "evidence": false
  },
  {
    "id": "6.3",
    "title": "Hands on the model: access and change control for the AI estate",
    "category": "Security",
    "read": "4 min",
    "extract": "Who can edit the system prompt? Who touched the training data? If the answer takes longer than a minute, the answer is 'too many people, unlogged.'",
    "isSample": false,
    "evidence": false
  },
  {
    "id": "6.4",
    "title": "The kill-switch: designing the ability to stop",
    "category": "Security",
    "read": "5 min",
    "extract": "Dual authorisation, defined triggers, rehearsed rollback. The off switch is a governance control that has to be built — because on the day you need it, you cannot improvise it.",
    "isSample": false,
    "evidence": false
  },
  {
    "id": "6.5",
    "title": "When AI fails: wiring it into incident response",
    "category": "Security",
    "read": "5 min",
    "extract": "Your IR plan knows what to do about ransomware. Ask it what to do when the pricing model goes wrong at scale, and listen to the silence.",
    "isSample": false,
    "evidence": false
  },
  {
    "id": "6.6",
    "title": "When the AI is down: operating without the machine",
    "category": "Security",
    "read": "4 min",
    "extract": "The quiet dependency test: which decisions stop, which customers wait, which staff no longer remember the manual process? Resilience is answering before the outage asks.",
    "isSample": false,
    "evidence": false
  },
  {
    "id": "6.7",
    "title": "The supply chain under the AI: assessing what you depend on",
    "category": "Security",
    "read": "4 min",
    "extract": "Behind the tool you bought sits a model you didn't, an API you can't see, and a dependency chain nobody mapped. Your security perimeter includes all of it.",
    "isSample": false,
    "evidence": false
  },
  {
    "id": "6.8",
    "title": "The declaration: evidencing AI controls the board can sign",
    "category": "Security",
    "read": "5 min",
    "extract": "From the 2026 reporting cycle, boards declare their material controls effective — and the FRC has said IT, cyber and AI are inside the boundary. Signing on assertion is no longer available.",
    "isSample": false,
    "evidence": false
  },
  {
    "id": "7.1",
    "title": "The literacy duty: the obligation already on your books",
    "category": "Workforce",
    "read": "5 min",
    "extract": "It has applied since February 2025. Enforcement starts in August 2026. The AI Act's quietest duty is the one most boards still think is next year's problem.",
    "isSample": true,
    "evidence": false
  },
  {
    "id": "7.2",
    "title": "Resourcing the overseer: competence, time, and standing",
    "category": "Workforce",
    "read": "5 min",
    "extract": "The law names the person: competent, trained, authorised, supported. Most organisations name them too — and then give them forty seconds per decision.",
    "isSample": false,
    "evidence": false
  },
  {
    "id": "7.3",
    "title": "Designing for intervention: systems humans can actually stop",
    "category": "Workforce",
    "read": "5 min",
    "extract": "Article 14 puts the duty on the system, not just the person: built so oversight is possible. A capable human in front of an opaque, urgent interface is a design failure wearing a compliance badge.",
    "isSample": false,
    "evidence": false
  },
  {
    "id": "7.4",
    "title": "Before the machine arrives: assessing the impact on people",
    "category": "Workforce",
    "read": "5 min",
    "extract": "The s172 duty is procedural: stakeholder impact considered, and minuted. For AI that changes jobs, the assessment is your safe harbour — and it has to predate the decision.",
    "isSample": false,
    "evidence": false
  },
  {
    "id": "7.5",
    "title": "Telling the workforce: information and consultation before go-live",
    "category": "Workforce",
    "read": "4 min",
    "extract": "The deployer duty is explicit: workers and their representatives informed before the system enters service. Finding out from the rollout email is the compliance failure and the trust failure in one.",
    "isSample": false,
    "evidence": false
  },
  {
    "id": "7.6",
    "title": "Augmentation first: the strategy that survives contact with the workforce",
    "category": "Workforce",
    "read": "5 min",
    "extract": "Redesign over elimination is not sentiment — it is the adoption strategy with the better failure profile, the better metrics, and the better story to every audience that matters.",
    "isSample": false,
    "evidence": false
  },
  {
    "id": "7.7",
    "title": "Shadow AI: governing the estate you didn't approve",
    "category": "Workforce",
    "read": "5 min",
    "extract": "Staff are already using AI you've never assessed — pasting into it, deciding with it, shipping from it. The governed response is a better catalogue, not a wider ban.",
    "isSample": false,
    "evidence": false
  },
  {
    "id": "7.8",
    "title": "Keeping the humans sharp: skill sustainability under automation",
    "category": "Workforce",
    "read": "5 min",
    "extract": "The fallback plan assumes people who can still do the work. Automation quietly retires that assumption — unless retention is designed, the capability your controls depend on decays on schedule.",
    "isSample": false,
    "evidence": false
  },
  {
    "id": "8.1",
    "title": "The value chain found you: mapping the obligations that arrive by contract",
    "category": "ESG",
    "read": "5 min",
    "extract": "Mandatory CSRD now stops at 1,000 employees and €450 million. Your obligations didn't stop — they changed carrier, and they now arrive in your customers' supplier questionnaires.",
    "isSample": true,
    "evidence": false
  },
  {
    "id": "8.2",
    "title": "The Basic Module: eleven disclosures that answer most of the mail",
    "category": "ESG",
    "read": "5 min",
    "extract": "B1 to B11 — profile, energy, emissions, workforce, safety, conduct. The VSME's Basic Module is the standardised answer to the questionnaire flood, and most of it is data you already hold.",
    "isSample": false,
    "evidence": false
  },
  {
    "id": "8.3",
    "title": "The Comprehensive Module: when finance and flagship clients want more",
    "category": "ESG",
    "read": "5 min",
    "extract": "Scope 3, targets, transition risk, human rights — the C-module asks harder questions. Answer them once, deliberately, for the counterparties whose business justifies it.",
    "isSample": false,
    "evidence": false
  },
  {
    "id": "8.4",
    "title": "The right to say no: holding the protected-undertaking line",
    "category": "ESG",
    "read": "4 min",
    "extract": "Under 1,000 employees, the law now caps what your big customers may demand: information beyond the voluntary standard can be refused. A right nobody exercises protects nobody.",
    "isSample": false,
    "evidence": false
  },
  {
    "id": "8.5",
    "title": "Counting the machine: the environmental footprint of your AI",
    "category": "ESG",
    "read": "5 min",
    "extract": "The AI Act now makes model providers disclose energy use — which means your AI footprint is becoming a knowable number. Buyers have started asking for it.",
    "isSample": false,
    "evidence": false
  },
  {
    "id": "8.6",
    "title": "Collect once, answer everywhere: the single sustainability dataset",
    "category": "ESG",
    "read": "4 min",
    "extract": "The same energy bill excavated six times a year is not a reporting burden — it is a filing failure. One dataset, owned and refreshed, collapses the marginal cost of every request to near zero.",
    "isSample": false,
    "evidence": false
  },
  {
    "id": "8.7",
    "title": "Someone senior, on the record: owning sustainability at board level",
    "category": "ESG",
    "read": "4 min",
    "extract": "The comprehensive standard asks it directly: who at senior level is accountable for sustainability? 'Whoever was asked last' is an answer — just not one that survives a questionnaire.",
    "isSample": false,
    "evidence": false
  },
  {
    "id": "8.8",
    "title": "Making it pay: converting ESG readiness into contracts and capital",
    "category": "ESG",
    "read": "5 min",
    "extract": "The dataset is built, the line is held, the owner is named. The last discipline is extraction: deliberately converting readiness into won tenders, kept clients, and better borrowing terms.",
    "isSample": false,
    "evidence": false
  }
];

export const GLOSSARY_META: GlossaryMeta[] = [
  {
    "term": "8×8 framework",
    "source": "Principled Futures",
    "related": [
      "1.1"
    ]
  },
  {
    "term": "Accountability file",
    "source": "UK GDPR Article 5(2)",
    "related": [
      "1.8",
      "5.8"
    ]
  },
  {
    "term": "Accountability rings",
    "source": "Principled Futures telemetry",
    "related": [
      "7.2"
    ]
  },
  {
    "term": "Adversarial input",
    "source": "EU AI Act robustness requirements",
    "related": [
      "6.1"
    ]
  },
  {
    "term": "AI Act (EU)",
    "source": "EU Regulation 2024/1689",
    "related": [
      "2.1",
      "1.6"
    ]
  },
  {
    "term": "AI literacy duty",
    "source": "EU AI Act Article 4",
    "related": [
      "7.1"
    ]
  },
  {
    "term": "AI register",
    "source": "Principled Futures framework",
    "related": [
      "1.4",
      "4.6"
    ]
  },
  {
    "term": "AI-washing",
    "related": [
      "4.8"
    ]
  },
  {
    "term": "Article 22B / 22C (UK GDPR)",
    "source": "Data (Use and Access) Act 2025",
    "related": [
      "3.4",
      "5.1",
      "5.2"
    ]
  },
  {
    "term": "Article 26 (EU AI Act)",
    "source": "EU AI Act Article 26",
    "related": [
      "2.4"
    ]
  },
  {
    "term": "Article 50 (EU AI Act)",
    "source": "EU AI Act Article 50",
    "related": [
      "4.1",
      "4.2"
    ]
  },
  {
    "term": "Assessment notice",
    "source": "UK Data Protection Act 2018",
    "related": [
      "1.7",
      "5.8"
    ]
  },
  {
    "term": "ATRS",
    "source": "UK Government / DSIT",
    "related": [
      "4.5"
    ]
  },
  {
    "term": "Augmentation-first",
    "source": "Principled Futures framework",
    "related": [
      "7.6"
    ]
  },
  {
    "term": "Automation bias",
    "related": [
      "7.3",
      "3.5"
    ]
  },
  {
    "term": "Balancing test",
    "source": "UK GDPR Article 6(1)(f)",
    "related": [
      "5.3"
    ]
  },
  {
    "term": "Basic Module (VSME)",
    "source": "EFRAG VSME",
    "related": [
      "8.2"
    ]
  },
  {
    "term": "Bias carve-out",
    "source": "EU Digital Omnibus",
    "related": [
      "3.2"
    ]
  },
  {
    "term": "Breach (telemetry)",
    "source": "Principled Futures telemetry",
    "related": [
      "2.2"
    ]
  },
  {
    "term": "Comprehensive Module (VSME)",
    "source": "EFRAG VSME",
    "related": [
      "8.3"
    ]
  },
  {
    "term": "Concentration risk",
    "related": [
      "6.6",
      "6.7"
    ]
  },
  {
    "term": "Containment",
    "source": "Principled Futures framework",
    "related": [
      "6.4"
    ]
  },
  {
    "term": "Contestability",
    "source": "DUAA / UK GDPR Article 22C",
    "related": [
      "4.4"
    ]
  },
  {
    "term": "CSRD",
    "source": "EU Directive, as amended by Omnibus I",
    "related": [
      "8.1"
    ]
  },
  {
    "term": "Data minimisation",
    "source": "UK GDPR Article 5(1)(c)",
    "related": [
      "5.6"
    ]
  },
  {
    "term": "Data poisoning",
    "source": "NCSC secure AI guidance",
    "related": [
      "6.1"
    ]
  },
  {
    "term": "Deepfake",
    "source": "EU AI Act Article 50",
    "related": [
      "4.2"
    ]
  },
  {
    "term": "Deployer",
    "source": "EU AI Act",
    "related": [
      "2.4"
    ]
  },
  {
    "term": "Disparate impact",
    "source": "Equality law practice",
    "related": [
      "3.3"
    ]
  },
  {
    "term": "DPIA",
    "source": "UK GDPR Article 35",
    "related": [
      "2.3",
      "5.4"
    ]
  },
  {
    "term": "DSIT",
    "source": "UK Government"
  },
  {
    "term": "Dual authorisation",
    "related": [
      "6.4"
    ]
  },
  {
    "term": "DUAA",
    "source": "UK statute",
    "related": [
      "5.1",
      "5.2"
    ]
  },
  {
    "term": "EFRAG",
    "source": "EU standard-setter",
    "related": [
      "8.2"
    ]
  },
  {
    "term": "Equality Act 2010",
    "source": "UK statute",
    "related": [
      "3.1"
    ]
  },
  {
    "term": "Explainability",
    "related": [
      "4.3",
      "4.5"
    ]
  },
  {
    "term": "Four safeguards",
    "source": "UK GDPR Article 22C",
    "related": [
      "4.4",
      "5.2"
    ]
  },
  {
    "term": "FRC",
    "source": "UK regulator",
    "related": [
      "1.1",
      "6.8"
    ]
  },
  {
    "term": "FRIA",
    "source": "EU AI Act Article 27",
    "related": [
      "2.3"
    ]
  },
  {
    "term": "GHG Protocol",
    "source": "GHG Protocol",
    "related": [
      "8.3"
    ]
  },
  {
    "term": "Hallucination",
    "related": [
      "2.7"
    ]
  },
  {
    "term": "Horizon scanning",
    "source": "Principled Futures framework",
    "related": [
      "1.6"
    ]
  },
  {
    "term": "Human intervention",
    "source": "UK GDPR Article 22C",
    "related": [
      "3.5",
      "4.4"
    ]
  },
  {
    "term": "ICO",
    "source": "UK regulator",
    "related": [
      "3.5"
    ]
  },
  {
    "term": "IDTA",
    "source": "UK GDPR transfer regime"
  },
  {
    "term": "Incident clocks",
    "source": "EU AI Act",
    "related": [
      "2.6",
      "6.5"
    ]
  },
  {
    "term": "ISO/IEC 42001",
    "source": "International standard",
    "related": [
      "1.7"
    ]
  },
  {
    "term": "Kill-switch",
    "source": "Principled Futures framework",
    "related": [
      "6.4"
    ]
  },
  {
    "term": "Lawful basis",
    "source": "UK GDPR Article 6",
    "related": [
      "5.3"
    ]
  },
  {
    "term": "Legitimate interests",
    "source": "UK GDPR Article 6(1)(f)",
    "related": [
      "5.3"
    ]
  },
  {
    "term": "Machine-readable marking",
    "source": "EU AI Act Article 50",
    "related": [
      "4.2"
    ]
  },
  {
    "term": "Maturity bands",
    "source": "Principled Futures framework"
  },
  {
    "term": "Meaningful human involvement",
    "source": "DUAA / ICO guidance",
    "related": [
      "3.5",
      "5.1"
    ]
  },
  {
    "term": "Model card",
    "related": [
      "3.3",
      "4.5"
    ]
  },
  {
    "term": "Model drift",
    "related": [
      "2.7"
    ]
  },
  {
    "term": "NCSC",
    "source": "UK agency",
    "related": [
      "6.2"
    ]
  },
  {
    "term": "Omnibus (Digital / Omnibus I)",
    "source": "EU legislation",
    "related": [
      "2.8",
      "8.1",
      "8.4"
    ]
  },
  {
    "term": "Parity band",
    "related": [
      "3.3"
    ]
  },
  {
    "term": "PECR",
    "source": "UK regulations"
  },
  {
    "term": "Prompt injection",
    "source": "NCSC secure AI guidance",
    "related": [
      "6.1"
    ]
  },
  {
    "term": "Protected characteristics",
    "source": "Equality Act 2010",
    "related": [
      "3.1"
    ]
  },
  {
    "term": "Protected undertaking",
    "source": "Omnibus I Directive",
    "related": [
      "8.4"
    ]
  },
  {
    "term": "Provider",
    "source": "EU AI Act"
  },
  {
    "term": "Provision 29",
    "source": "UK Corporate Governance Code 2024",
    "related": [
      "1.1",
      "6.8"
    ]
  },
  {
    "term": "Proxy variable",
    "related": [
      "3.2"
    ]
  },
  {
    "term": "RACI",
    "related": [
      "1.2"
    ]
  },
  {
    "term": "Recognised legitimate interests",
    "source": "UK GDPR Article 6(1)(ea)",
    "related": [
      "5.3"
    ]
  },
  {
    "term": "Red-teaming",
    "related": [
      "6.1",
      "1.7"
    ]
  },
  {
    "term": "Ring (accountability)",
    "source": "Principled Futures telemetry",
    "related": [
      "7.2"
    ]
  },
  {
    "term": "Risk appetite",
    "source": "Principled Futures framework",
    "related": [
      "2.2"
    ]
  },
  {
    "term": "Risk tiers (AI Act)",
    "source": "EU AI Act",
    "related": [
      "2.1"
    ]
  },
  {
    "term": "s172 (Companies Act)",
    "source": "Companies Act 2006",
    "related": [
      "1.8",
      "7.4"
    ]
  },
  {
    "term": "Scope 1, 2 and 3",
    "source": "GHG Protocol",
    "related": [
      "8.2",
      "8.3"
    ]
  },
  {
    "term": "Shadow AI",
    "source": "Principled Futures framework",
    "related": [
      "7.7"
    ]
  },
  {
    "term": "Significant decision",
    "source": "UK GDPR Article 22A",
    "related": [
      "5.1"
    ]
  },
  {
    "term": "Solely automated",
    "source": "UK GDPR Article 22A",
    "related": [
      "5.1",
      "3.5"
    ]
  },
  {
    "term": "Special-category data",
    "source": "UK GDPR Article 9",
    "related": [
      "3.4",
      "5.5"
    ]
  },
  {
    "term": "Subject access request",
    "source": "UK GDPR Article 15",
    "related": [
      "5.7"
    ]
  },
  {
    "term": "Telemetry",
    "source": "Principled Futures",
    "related": [
      "2.7"
    ]
  },
  {
    "term": "Threshold",
    "source": "Principled Futures telemetry",
    "related": [
      "2.2"
    ]
  },
  {
    "term": "Transparency paradox",
    "related": [
      "4.5"
    ]
  },
  {
    "term": "Twin Transition",
    "source": "EU policy",
    "related": [
      "8.5"
    ]
  },
  {
    "term": "UK Corporate Governance Code 2024",
    "source": "FRC",
    "related": [
      "1.1"
    ]
  },
  {
    "term": "Value chain",
    "source": "CSRD",
    "related": [
      "8.1"
    ]
  },
  {
    "term": "VSME",
    "source": "EFRAG",
    "related": [
      "8.2",
      "8.3"
    ]
  },
  {
    "term": "Watermarking",
    "source": "EU AI Act Article 50",
    "related": [
      "4.2"
    ]
  }
];

export const GUIDE_META: GuideMeta[] = [
  {
    "id": "how-scoring-works",
    "title": "How scoring works"
  },
  {
    "id": "running-the-assessment",
    "title": "Running the assessment"
  },
  {
    "id": "maturity-bands",
    "title": "The five maturity bands"
  },
  {
    "id": "assigning-owners",
    "title": "Assigning metric owners"
  },
  {
    "id": "reading-the-report",
    "title": "Reading the advisory report"
  },
  {
    "id": "demo-data",
    "title": "What demo data means"
  },
  {
    "id": "regulatory-countdown",
    "title": "The regulatory countdown"
  },
  {
    "id": "your-data",
    "title": "Where your data lives"
  }
];

/** Briefing metadata for a criterion id, or undefined if none exists. */
export function articleFor(criterionId: string): ArticleMeta | undefined {
  return ARTICLE_META.find((a) => a.id === criterionId);
}

/** Glossary terms grouped by initial letter, for the A–Z index. */
export function glossaryGroups(): { letter: string; entries: GlossaryMeta[] }[] {
  const map = new Map<string, GlossaryMeta[]>();
  for (const e of GLOSSARY_META) {
    const letter = e.term[0].toUpperCase();
    const key = /[A-Z]/.test(letter) ? letter : "#";
    if (!map.has(key)) map.set(key, []);
    map.get(key)!.push(e);
  }
  return [...map.entries()].sort((a, b) => a[0].localeCompare(b[0])).map(([letter, entries]) => ({ letter, entries }));
}
