// src/lib/content-meta.ts
// GENERATED by scripts/seed-content.mjs — do not edit by hand.
// Metadata only: titles, categories, standfirsts. Body prose and glossary
// definitions live in the database (see supabase/migrations/0004_content_tables.sql)
// and are fetched per-user by src/lib/content.ts.

export interface ArticleMeta { id: string; title: string; category: string; read: string; extract: string; isSample: boolean; evidence: boolean }
export interface GlossaryMeta { term: string; source?: string; related?: string[] }
export interface GuideMeta { id: string; title: string }

export const ARTICLE_META: ArticleMeta[] = [
  {
    "id": "1.1",
    "title": "Board mandate",
    "category": "Governance",
    "read": "1 min",
    "extract": "Whether oversight of AI is written into the remit of the board or a named committee, reported on regularly, and recorded in the minutes.",
    "isSample": true,
    "evidence": true
  },
  {
    "id": "1.2",
    "title": "Roles and decision rights",
    "category": "Governance",
    "read": "1 min",
    "extract": "Whether each use of AI has a named person answerable for what it does, with the authority to change or stop it, and a known route for taking concerns upward.",
    "isSample": false,
    "evidence": true
  },
  {
    "id": "1.3",
    "title": "Policy architecture",
    "category": "Governance",
    "read": "1 min",
    "extract": "Whether there is a small set of approved, current policies: what AI may be used for, which tools staff may use with what data, and what happens when something goes wrong.",
    "isSample": false,
    "evidence": true
  },
  {
    "id": "1.4",
    "title": "AI inventory and register",
    "category": "Governance",
    "read": "1 min",
    "extract": "Whether there is one maintained list of every AI system in use, including AI bought in and AI built into other software, with purpose, owner, data and risk recorded for each.",
    "isSample": false,
    "evidence": true
  },
  {
    "id": "1.5",
    "title": "Third-party and procurement governance",
    "category": "Governance",
    "read": "1 min",
    "extract": "Whether bought-in AI is examined before adoption and for as long as it is used: questions asked, answers tested, terms written into the contract, and a way out if the supplier fails.",
    "isSample": false,
    "evidence": true
  },
  {
    "id": "1.6",
    "title": "Regulatory horizon scanning",
    "category": "Governance",
    "read": "1 min",
    "extract": "Whether someone is responsible for watching the rules that govern the organisation's AI, on a set rhythm, with a record of what changed, what it meant and what was done.",
    "isSample": false,
    "evidence": true
  },
  {
    "id": "1.7",
    "title": "Independent assurance",
    "category": "Governance",
    "read": "1 min",
    "extract": "Whether anyone outside the team that runs AI governance checks that it works: a review that is scoped, scheduled, carried out by someone free to disagree, and followed through.",
    "isSample": false,
    "evidence": true
  },
  {
    "id": "1.8",
    "title": "Documentation and records",
    "category": "Governance",
    "read": "1 min",
    "extract": "Whether the organisation can show, from records made at the time, how each AI system came to be approved, on what evidence, by whom, and what has been reviewed since.",
    "isSample": false,
    "evidence": true
  },
  {
    "id": "2.1",
    "title": "Risk identification and classification",
    "category": "Risk",
    "read": "1 min",
    "extract": "Whether every AI system in use, including tools bought in or embedded in other software, has been assigned a risk tier by a written method, with the reasoning kept.",
    "isSample": true,
    "evidence": true
  },
  {
    "id": "2.2",
    "title": "Risk appetite",
    "category": "Risk",
    "read": "1 min",
    "extract": "Whether the board has written down which uses of AI it will pursue, which it will allow only with controls, and which it refuses, in terms specific enough to settle a real decision.",
    "isSample": false,
    "evidence": true
  },
  {
    "id": "2.3",
    "title": "Impact assessments",
    "category": "Risk",
    "read": "1 min",
    "extract": "Whether the effect of an AI system on people's data and on their wider rights is assessed before it goes live, as one joined exercise.",
    "isSample": false,
    "evidence": true
  },
  {
    "id": "2.4",
    "title": "Deployer operational controls",
    "category": "Risk",
    "read": "1 min",
    "extract": "Whether AI bought from others is run as its provider specifies, on checked input data, with its behaviour watched and its logs kept.",
    "isSample": false,
    "evidence": true
  },
  {
    "id": "2.5",
    "title": "Risk treatment",
    "category": "Risk",
    "read": "1 min",
    "extract": "Whether every AI risk the organisation has identified carries a recorded decision (reduce it, share it, stop the activity or accept it) with a named person, a date and a check that the action worked.",
    "isSample": false,
    "evidence": true
  },
  {
    "id": "2.6",
    "title": "Incident readiness and suspension",
    "category": "Risk",
    "read": "1 min",
    "extract": "Whether the organisation would notice an AI system causing harm, has someone with authority to stop it, and knows whom it must tell and how quickly.",
    "isSample": false,
    "evidence": true
  },
  {
    "id": "2.7",
    "title": "Ongoing monitoring",
    "category": "Risk",
    "read": "1 min",
    "extract": "Whether the risk of each AI system is looked at again after it goes live, on a schedule and whenever something material changes.",
    "isSample": false,
    "evidence": true
  },
  {
    "id": "2.8",
    "title": "Proportionality and documentation",
    "category": "Risk",
    "read": "1 min",
    "extract": "Whether the depth of risk work matches the organisation's size and the stakes of each system, and whether there is a record to show for it.",
    "isSample": false,
    "evidence": true
  },
  {
    "id": "3.1",
    "title": "Discrimination risk awareness",
    "category": "Ethics & Fairness",
    "read": "1 min",
    "extract": "Whether the organisation knows where its AI could treat people worse because of who they are: each AI use set against the protected characteristics it could affect, with a named owner.",
    "isSample": true,
    "evidence": true
  },
  {
    "id": "3.2",
    "title": "Bias in data",
    "category": "Ethics & Fairness",
    "read": "1 min",
    "extract": "Whether data is examined for inherited unfairness before it informs decisions about people: where it came from, who is missing, and which ordinary-looking fields stand in for protected characteristics.",
    "isSample": false,
    "evidence": true
  },
  {
    "id": "3.3",
    "title": "Bias testing",
    "category": "Ethics & Fairness",
    "read": "1 min",
    "extract": "Whether the organisation checks what its AI does to different groups: outcomes compared across groups, against thresholds set beforehand, recorded, and repeated after launch.",
    "isSample": false,
    "evidence": true
  },
  {
    "id": "3.4",
    "title": "Special-category data controls",
    "category": "Ethics & Fairness",
    "read": "1 min",
    "extract": "Whether the organisation stops sensitive personal data from driving automated decisions about people unless a lawful exception applies, and whether that rule is enforced.",
    "isSample": false,
    "evidence": true
  },
  {
    "id": "3.5",
    "title": "Meaningful human review",
    "category": "Ethics & Fairness",
    "read": "1 min",
    "extract": "Whether the people who review AI-supported decisions can change them: competent to judge the output, authorised to overrule it, and able to see how it was reached.",
    "isSample": false,
    "evidence": true
  },
  {
    "id": "3.6",
    "title": "Ethical review",
    "category": "Ethics & Fairness",
    "read": "1 min",
    "extract": "Whether there is a defined point before deployment where ethical concerns are heard, and where the reviewers can require changes or refuse outright.",
    "isSample": false,
    "evidence": true
  },
  {
    "id": "3.7",
    "title": "Vendor fairness assurance",
    "category": "Ethics & Fairness",
    "read": "1 min",
    "extract": "Whether a supplier's statement that its AI is fair is tested before the organisation relies on it: evidence asked for, read, re-checked, and backed by contract terms that give a right to look.",
    "isSample": false,
    "evidence": true
  },
  {
    "id": "3.8",
    "title": "Remediation and redress",
    "category": "Ethics & Fairness",
    "read": "1 min",
    "extract": "Whether, when AI is found to have treated people unfairly, the organisation corrects the system, re-examines the decisions it influenced and puts the affected people right.",
    "isSample": false,
    "evidence": true
  },
  {
    "id": "4.1",
    "title": "AI-interaction disclosure",
    "category": "Transparency",
    "read": "1 min",
    "extract": "Whether people are told, at the point of contact, that they are dealing with an AI system and not a person, under a written standard covering every channel.",
    "isSample": true,
    "evidence": true
  },
  {
    "id": "4.2",
    "title": "Synthetic-content marking",
    "category": "Transparency",
    "read": "1 min",
    "extract": "Whether text, images, audio and video produced by the organisation's AI carry a mark that software can detect, and a visible label where the law requires one.",
    "isSample": false,
    "evidence": true
  },
  {
    "id": "4.3",
    "title": "Decision-specific explanation",
    "category": "Transparency",
    "read": "1 min",
    "extract": "Whether the organisation can tell a person why an AI-supported decision about them came out as it did: the factors that mattered in their case, in plain words.",
    "isSample": false,
    "evidence": true
  },
  {
    "id": "4.4",
    "title": "Contestability",
    "category": "Transparency",
    "read": "1 min",
    "extract": "Whether a person affected by a significant automated decision can put their side, have a person look at it again and challenge the outcome, by a route that works in practice.",
    "isSample": false,
    "evidence": true
  },
  {
    "id": "4.5",
    "title": "Explainability by design",
    "category": "Transparency",
    "read": "1 min",
    "extract": "Whether the ability to explain an AI system's outputs is settled before the system is bought or built: written into the specification and the contract, and kept current.",
    "isSample": false,
    "evidence": true
  },
  {
    "id": "4.6",
    "title": "Internal transparency",
    "category": "Transparency",
    "read": "1 min",
    "extract": "Whether the organisation can describe its own AI: a complete, current record of each system: purpose, a plain summary of how it works, data used, named owner.",
    "isSample": false,
    "evidence": true
  },
  {
    "id": "4.7",
    "title": "Notification of automated decisions",
    "category": "Transparency",
    "read": "1 min",
    "extract": "Whether people are told, promptly and plainly, that a significant decision about them was made by a machine, and what they can do about it.",
    "isSample": false,
    "evidence": true
  },
  {
    "id": "4.8",
    "title": "External reporting honesty",
    "category": "Transparency",
    "read": "1 min",
    "extract": "Whether public statements about the organisation's AI (marketing, bids, investor material, the annual report) are checked against what the systems really do before publication, and who signs that off.",
    "isSample": false,
    "evidence": true
  },
  {
    "id": "5.1",
    "title": "Automated-decision scoping",
    "category": "Governance",
    "read": "1 min",
    "extract": "Whether the organisation has worked out, system by system and in writing, which of its decisions about people are significant and taken with no meaningful human involvement.",
    "isSample": true,
    "evidence": true
  },
  {
    "id": "5.2",
    "title": "Safeguards implementation",
    "category": "Governance",
    "read": "1 min",
    "extract": "Whether the four safeguards the law attaches to significant, solely automated decisions exist as working processes, each with an owner, a route, a record and a test.",
    "isSample": false,
    "evidence": true
  },
  {
    "id": "5.3",
    "title": "Lawful basis",
    "category": "Governance",
    "read": "1 min",
    "extract": "Whether the organisation can name a valid legal ground for each use of personal data in its AI: training, the data fed in, and what the system says about people.",
    "isSample": false,
    "evidence": true
  },
  {
    "id": "5.4",
    "title": "DPIA discipline",
    "category": "Governance",
    "read": "1 min",
    "extract": "Whether data protection impact assessments are triggered when they should be, done in depth, and acted on: findings change the design, and the assessment is revisited when the system changes.",
    "isSample": false,
    "evidence": true
  },
  {
    "id": "5.5",
    "title": "Special-category handling",
    "category": "Governance",
    "read": "1 min",
    "extract": "Whether the organisation knows where sensitive personal data enters its AI systems (at collection, in training data and in what a system infers) and whether each use rests on a documented lawful condition.",
    "isSample": false,
    "evidence": true
  },
  {
    "id": "5.6",
    "title": "Data quality and minimisation",
    "category": "Governance",
    "read": "1 min",
    "extract": "Whether data fed to AI systems meets a written standard: relevant to the purpose, representative of the people decided about, accurate, and no more than the purpose requires.",
    "isSample": false,
    "evidence": true
  },
  {
    "id": "5.7",
    "title": "Rights readiness",
    "category": "Governance",
    "read": "1 min",
    "extract": "Whether the organisation can find, correct, delete or stop using a person's data when they ask, including data in AI training sets, outputs, profiles and suppliers' systems, within the legal time limit.",
    "isSample": false,
    "evidence": true
  },
  {
    "id": "5.8",
    "title": "Records and accountability",
    "category": "Governance",
    "read": "1 min",
    "extract": "Whether the organisation can prove, from records made at the time, how each AI system uses personal data: scope, legal basis, risk assessment, safeguards and decisions taken.",
    "isSample": false,
    "evidence": true
  },
  {
    "id": "6.1",
    "title": "AI threat awareness",
    "category": "Security",
    "read": "1 min",
    "extract": "Whether the organisation knows the ways an AI system can be attacked that ordinary software cannot, and has written down which of them apply to each system it runs.",
    "isSample": true,
    "evidence": true
  },
  {
    "id": "6.2",
    "title": "Secure development and procurement",
    "category": "Security",
    "read": "1 min",
    "extract": "Whether there is a written security standard that every AI system must meet, both those the organisation builds and those it buys, and whether anyone checks that it is met.",
    "isSample": false,
    "evidence": true
  },
  {
    "id": "6.3",
    "title": "Access and change control",
    "category": "Security",
    "read": "1 min",
    "extract": "Whether the organisation knows who can change what an AI system does (its model, prompts, training data and data pipelines), limits that to those who need it, and keeps a record of every change.",
    "isSample": false,
    "evidence": true
  },
  {
    "id": "6.4",
    "title": "Containment and kill-switch",
    "category": "Security",
    "read": "1 min",
    "extract": "Whether each AI system can be stopped quickly, by people who have the authority to do it and know how, and whether that has been tried.",
    "isSample": false,
    "evidence": true
  },
  {
    "id": "6.5",
    "title": "Incident response integration",
    "category": "Security",
    "read": "1 min",
    "extract": "Whether a failing AI system triggers the organisation's existing incident response: named scenarios, known reporting duties, rehearsal, and lessons fed back.",
    "isSample": false,
    "evidence": true
  },
  {
    "id": "6.6",
    "title": "Resilience and recovery",
    "category": "Security",
    "read": "1 min",
    "extract": "Whether the business can keep serving people when an AI system is unavailable, withdrawn or switched off, and how quickly it can recover.",
    "isSample": false,
    "evidence": true
  },
  {
    "id": "6.7",
    "title": "Supply-chain security",
    "category": "Security",
    "read": "1 min",
    "extract": "Whether the organisation knows what its AI depends on (the supplier, the underlying model, the interfaces, the data flows) and has assessed the security of each, before adoption and after.",
    "isSample": false,
    "evidence": true
  },
  {
    "id": "6.8",
    "title": "Board-level security assurance",
    "category": "Security",
    "read": "1 min",
    "extract": "Whether the board holds evidence that its controls over AI work, enough to support a public statement that the company's material controls are effective.",
    "isSample": false,
    "evidence": true
  },
  {
    "id": "7.1",
    "title": "AI literacy",
    "category": "Workforce",
    "read": "1 min",
    "extract": "Whether the people who use AI for the organisation, employees and contractors alike, know enough to use it safely, and whether records show it.",
    "isSample": true,
    "evidence": true
  },
  {
    "id": "7.2",
    "title": "Oversight capability",
    "category": "Workforce",
    "read": "1 min",
    "extract": "Whether those assigned to oversee AI systems can do the job: trained on the system, given time for each case, and free to overrule it.",
    "isSample": false,
    "evidence": true
  },
  {
    "id": "7.3",
    "title": "Oversight by design",
    "category": "Workforce",
    "read": "1 min",
    "extract": "Whether systems are set up so a person can step in: a point to intervene before an output takes effect, reasons on screen, time to act and a way to stop.",
    "isSample": false,
    "evidence": true
  },
  {
    "id": "7.4",
    "title": "Workforce impact assessment",
    "category": "Workforce",
    "read": "1 min",
    "extract": "Whether the effect on jobs is assessed in writing before the board decides to adopt AI that changes work, and whether the board's consideration is minuted.",
    "isSample": false,
    "evidence": true
  },
  {
    "id": "7.5",
    "title": "Worker information and consultation",
    "category": "Workforce",
    "read": "1 min",
    "extract": "Whether the people who will work with an AI system, or be managed by it, are told before it starts, and whether what they say can still change it.",
    "isSample": false,
    "evidence": true
  },
  {
    "id": "7.6",
    "title": "Augmentation-first strategy",
    "category": "Workforce",
    "read": "1 min",
    "extract": "Whether the default, when AI changes a job, is to redesign the work around people, and whether success is measured by output and quality instead of posts removed.",
    "isSample": false,
    "evidence": true
  },
  {
    "id": "7.7",
    "title": "Acceptable use and shadow AI",
    "category": "Workforce",
    "read": "1 min",
    "extract": "Whether staff know which AI tools they may use and for what, and whether the organisation finds out about the tools it never approved.",
    "isSample": false,
    "evidence": true
  },
  {
    "id": "7.8",
    "title": "Skill sustainability",
    "category": "Workforce",
    "read": "1 min",
    "extract": "Whether the organisation knows which human skills it must keep as AI takes over tasks, and has a way of keeping them in use.",
    "isSample": false,
    "evidence": true
  },
  {
    "id": "8.1",
    "title": "Value-chain position",
    "category": "ESG",
    "read": "1 min",
    "extract": "Whether the organisation knows which customers, lenders and public buyers must report on sustainability, which duties reach it as a supplier, and what each may ask.",
    "isSample": true,
    "evidence": true
  },
  {
    "id": "8.2",
    "title": "Basic sustainability data",
    "category": "ESG",
    "read": "1 min",
    "extract": "Whether the organisation can produce the basic data set that the EU's voluntary standard defines: energy, emissions, water, waste, workforce, safety, pay and conduct.",
    "isSample": false,
    "evidence": true
  },
  {
    "id": "8.3",
    "title": "Comprehensive readiness",
    "category": "ESG",
    "read": "1 min",
    "extract": "Whether, where a lender or major client requires it, the organisation can answer the fuller set: strategy, emissions targets, climate risks, human rights policies and incidents, and value-chain emissions.",
    "isSample": false,
    "evidence": true
  },
  {
    "id": "8.4",
    "title": "The protected-undertaking line",
    "category": "ESG",
    "read": "1 min",
    "extract": "Whether the organisation knows the legal limit on what a large customer may demand for its own sustainability report, and uses it.",
    "isSample": false,
    "evidence": true
  },
  {
    "id": "8.5",
    "title": "AI environmental footprint",
    "category": "ESG",
    "read": "1 min",
    "extract": "Whether the organisation knows how much energy, water and carbon its use of AI accounts for, and whether that shapes the models and suppliers it chooses.",
    "isSample": false,
    "evidence": true
  },
  {
    "id": "8.6",
    "title": "Sustainability data quality",
    "category": "ESG",
    "read": "1 min",
    "extract": "Whether sustainability figures are gathered once, from a known source, with an owner and a written method, and then reused for every customer, lender and report.",
    "isSample": false,
    "evidence": true
  },
  {
    "id": "8.7",
    "title": "Sustainability governance",
    "category": "ESG",
    "read": "1 min",
    "extract": "Whether one senior person is answerable for sustainability, and whether the board sees performance figures on a set timetable.",
    "isSample": false,
    "evidence": true
  },
  {
    "id": "8.8",
    "title": "Commercial leverage",
    "category": "ESG",
    "read": "1 min",
    "extract": "Whether the organisation uses its sustainability evidence on purpose, in bids and in finance conversations, and records whether it made a difference.",
    "isSample": false,
    "evidence": true
  }
];

export const GLOSSARY_META: GlossaryMeta[] = [
  {
    "term": "8×8 framework",
    "source": "Principled Futures",
    "related": [
      "1.1"
    ]
  },
  {
    "term": "Accountability file",
    "source": "UK GDPR Article 5(2)",
    "related": [
      "1.8",
      "5.8"
    ]
  },
  {
    "term": "Accountability rings",
    "source": "Principled Futures telemetry",
    "related": [
      "7.2"
    ]
  },
  {
    "term": "Adversarial input",
    "source": "EU AI Act robustness requirements",
    "related": [
      "6.1"
    ]
  },
  {
    "term": "AI Act (EU)",
    "source": "EU Regulation 2024/1689",
    "related": [
      "2.1",
      "1.6"
    ]
  },
  {
    "term": "AI literacy duty",
    "source": "EU AI Act Article 4",
    "related": [
      "7.1"
    ]
  },
  {
    "term": "AI register",
    "source": "Principled Futures framework",
    "related": [
      "1.4",
      "4.6"
    ]
  },
  {
    "term": "AI-washing",
    "related": [
      "4.8"
    ]
  },
  {
    "term": "Article 22B / 22C (UK GDPR)",
    "source": "Data (Use and Access) Act 2025",
    "related": [
      "3.4",
      "5.1",
      "5.2"
    ]
  },
  {
    "term": "Article 26 (EU AI Act)",
    "source": "EU AI Act Article 26",
    "related": [
      "2.4"
    ]
  },
  {
    "term": "Article 50 (EU AI Act)",
    "source": "EU AI Act Article 50",
    "related": [
      "4.1",
      "4.2"
    ]
  },
  {
    "term": "Assessment notice",
    "source": "UK Data Protection Act 2018",
    "related": [
      "1.7",
      "5.8"
    ]
  },
  {
    "term": "ATRS",
    "source": "UK Government / DSIT",
    "related": [
      "4.5"
    ]
  },
  {
    "term": "Augmentation-first",
    "source": "Principled Futures framework",
    "related": [
      "7.6"
    ]
  },
  {
    "term": "Automation bias",
    "related": [
      "7.3",
      "3.5"
    ]
  },
  {
    "term": "Balancing test",
    "source": "UK GDPR Article 6(1)(f)",
    "related": [
      "5.3"
    ]
  },
  {
    "term": "Basic Module (VSME)",
    "source": "EFRAG VSME",
    "related": [
      "8.2"
    ]
  },
  {
    "term": "Bias carve-out",
    "source": "EU Digital Omnibus",
    "related": [
      "3.2"
    ]
  },
  {
    "term": "Breach (telemetry)",
    "source": "Principled Futures telemetry",
    "related": [
      "2.2"
    ]
  },
  {
    "term": "Comprehensive Module (VSME)",
    "source": "EFRAG VSME",
    "related": [
      "8.3"
    ]
  },
  {
    "term": "Concentration risk",
    "related": [
      "6.6",
      "6.7"
    ]
  },
  {
    "term": "Containment",
    "source": "Principled Futures framework",
    "related": [
      "6.4"
    ]
  },
  {
    "term": "Contestability",
    "source": "DUAA / UK GDPR Article 22C",
    "related": [
      "4.4"
    ]
  },
  {
    "term": "CSRD",
    "source": "EU Directive, as amended by Omnibus I",
    "related": [
      "8.1"
    ]
  },
  {
    "term": "Data minimisation",
    "source": "UK GDPR Article 5(1)(c)",
    "related": [
      "5.6"
    ]
  },
  {
    "term": "Data poisoning",
    "source": "NCSC secure AI guidance",
    "related": [
      "6.1"
    ]
  },
  {
    "term": "Deepfake",
    "source": "EU AI Act Article 50",
    "related": [
      "4.2"
    ]
  },
  {
    "term": "Deployer",
    "source": "EU AI Act",
    "related": [
      "2.4"
    ]
  },
  {
    "term": "Disparate impact",
    "source": "Equality law practice",
    "related": [
      "3.3"
    ]
  },
  {
    "term": "DPIA",
    "source": "UK GDPR Article 35",
    "related": [
      "2.3",
      "5.4"
    ]
  },
  {
    "term": "DSIT",
    "source": "UK Government"
  },
  {
    "term": "Dual authorisation",
    "related": [
      "6.4"
    ]
  },
  {
    "term": "DUAA",
    "source": "UK statute",
    "related": [
      "5.1",
      "5.2"
    ]
  },
  {
    "term": "EFRAG",
    "source": "EU standard-setter",
    "related": [
      "8.2"
    ]
  },
  {
    "term": "Equality Act 2010",
    "source": "UK statute",
    "related": [
      "3.1"
    ]
  },
  {
    "term": "Explainability",
    "related": [
      "4.3",
      "4.5"
    ]
  },
  {
    "term": "Four safeguards",
    "source": "UK GDPR Article 22C",
    "related": [
      "4.4",
      "5.2"
    ]
  },
  {
    "term": "FRC",
    "source": "UK regulator",
    "related": [
      "1.1",
      "6.8"
    ]
  },
  {
    "term": "FRIA",
    "source": "EU AI Act Article 27",
    "related": [
      "2.3"
    ]
  },
  {
    "term": "GHG Protocol",
    "source": "GHG Protocol",
    "related": [
      "8.3"
    ]
  },
  {
    "term": "Hallucination",
    "related": [
      "2.7"
    ]
  },
  {
    "term": "Horizon scanning",
    "source": "Principled Futures framework",
    "related": [
      "1.6"
    ]
  },
  {
    "term": "Human intervention",
    "source": "UK GDPR Article 22C",
    "related": [
      "3.5",
      "4.4"
    ]
  },
  {
    "term": "ICO",
    "source": "UK regulator",
    "related": [
      "3.5"
    ]
  },
  {
    "term": "IDTA",
    "source": "UK GDPR transfer regime"
  },
  {
    "term": "Incident clocks",
    "source": "EU AI Act",
    "related": [
      "2.6",
      "6.5"
    ]
  },
  {
    "term": "ISO/IEC 42001",
    "source": "International standard",
    "related": [
      "1.7"
    ]
  },
  {
    "term": "Kill-switch",
    "source": "Principled Futures framework",
    "related": [
      "6.4"
    ]
  },
  {
    "term": "Lawful basis",
    "source": "UK GDPR Article 6",
    "related": [
      "5.3"
    ]
  },
  {
    "term": "Legitimate interests",
    "source": "UK GDPR Article 6(1)(f)",
    "related": [
      "5.3"
    ]
  },
  {
    "term": "Machine-readable marking",
    "source": "EU AI Act Article 50",
    "related": [
      "4.2"
    ]
  },
  {
    "term": "Maturity bands",
    "source": "Principled Futures framework"
  },
  {
    "term": "Meaningful human involvement",
    "source": "DUAA / ICO guidance",
    "related": [
      "3.5",
      "5.1"
    ]
  },
  {
    "term": "Model card",
    "related": [
      "3.3",
      "4.5"
    ]
  },
  {
    "term": "Model drift",
    "related": [
      "2.7"
    ]
  },
  {
    "term": "NCSC",
    "source": "UK agency",
    "related": [
      "6.2"
    ]
  },
  {
    "term": "Omnibus (Digital / Omnibus I)",
    "source": "EU legislation",
    "related": [
      "2.8",
      "8.1",
      "8.4"
    ]
  },
  {
    "term": "Parity band",
    "related": [
      "3.3"
    ]
  },
  {
    "term": "PECR",
    "source": "UK regulations"
  },
  {
    "term": "Prompt injection",
    "source": "NCSC secure AI guidance",
    "related": [
      "6.1"
    ]
  },
  {
    "term": "Protected characteristics",
    "source": "Equality Act 2010",
    "related": [
      "3.1"
    ]
  },
  {
    "term": "Protected undertaking",
    "source": "Omnibus I Directive",
    "related": [
      "8.4"
    ]
  },
  {
    "term": "Provider",
    "source": "EU AI Act"
  },
  {
    "term": "Provision 29",
    "source": "UK Corporate Governance Code 2024",
    "related": [
      "1.1",
      "6.8"
    ]
  },
  {
    "term": "Proxy variable",
    "related": [
      "3.2"
    ]
  },
  {
    "term": "RACI",
    "related": [
      "1.2"
    ]
  },
  {
    "term": "Recognised legitimate interests",
    "source": "UK GDPR Article 6(1)(ea)",
    "related": [
      "5.3"
    ]
  },
  {
    "term": "Red-teaming",
    "related": [
      "6.1",
      "1.7"
    ]
  },
  {
    "term": "Ring (accountability)",
    "source": "Principled Futures telemetry",
    "related": [
      "7.2"
    ]
  },
  {
    "term": "Risk appetite",
    "source": "Principled Futures framework",
    "related": [
      "2.2"
    ]
  },
  {
    "term": "Risk tiers (AI Act)",
    "source": "EU AI Act",
    "related": [
      "2.1"
    ]
  },
  {
    "term": "s172 (Companies Act)",
    "source": "Companies Act 2006",
    "related": [
      "1.8",
      "7.4"
    ]
  },
  {
    "term": "Scope 1, 2 and 3",
    "source": "GHG Protocol",
    "related": [
      "8.2",
      "8.3"
    ]
  },
  {
    "term": "Shadow AI",
    "source": "Principled Futures framework",
    "related": [
      "7.7"
    ]
  },
  {
    "term": "Significant decision",
    "source": "UK GDPR Article 22A",
    "related": [
      "5.1"
    ]
  },
  {
    "term": "Solely automated",
    "source": "UK GDPR Article 22A",
    "related": [
      "5.1",
      "3.5"
    ]
  },
  {
    "term": "Special-category data",
    "source": "UK GDPR Article 9",
    "related": [
      "3.4",
      "5.5"
    ]
  },
  {
    "term": "Subject access request",
    "source": "UK GDPR Article 15",
    "related": [
      "5.7"
    ]
  },
  {
    "term": "Telemetry",
    "source": "Principled Futures",
    "related": [
      "2.7"
    ]
  },
  {
    "term": "Threshold",
    "source": "Principled Futures telemetry",
    "related": [
      "2.2"
    ]
  },
  {
    "term": "Transparency paradox",
    "related": [
      "4.5"
    ]
  },
  {
    "term": "Twin Transition",
    "source": "EU policy",
    "related": [
      "8.5"
    ]
  },
  {
    "term": "UK Corporate Governance Code 2024",
    "source": "FRC",
    "related": [
      "1.1"
    ]
  },
  {
    "term": "Value chain",
    "source": "CSRD",
    "related": [
      "8.1"
    ]
  },
  {
    "term": "VSME",
    "source": "EFRAG",
    "related": [
      "8.2",
      "8.3"
    ]
  },
  {
    "term": "Watermarking",
    "source": "EU AI Act Article 50",
    "related": [
      "4.2"
    ]
  }
];

export const GUIDE_META: GuideMeta[] = [
  {
    "id": "how-scoring-works",
    "title": "How scoring works"
  },
  {
    "id": "running-the-assessment",
    "title": "Running the assessment"
  },
  {
    "id": "maturity-bands",
    "title": "The five maturity bands"
  },
  {
    "id": "assigning-owners",
    "title": "Assigning metric owners"
  },
  {
    "id": "reading-the-report",
    "title": "Reading the advisory report"
  },
  {
    "id": "demo-data",
    "title": "What demo data means"
  },
  {
    "id": "regulatory-countdown",
    "title": "The regulatory countdown"
  },
  {
    "id": "your-data",
    "title": "Where your data lives"
  }
];

export const LIBRARY_STATS = {
  "documents": 659,
  "citations": 1151,
  "anchors": 168,
  "byType": {
    "legislation": 163,
    "code or standard": 67,
    "regulator guidance": 149,
    "official report": 83,
    "research": 148,
    "court or tribunal": 11,
    "professional": 17,
    "enforcement decision": 15,
    "reporting framework": 6
  },
  "byJurisdiction": {
    "UK": 383,
    "US": 61,
    "other": 22,
    "International": 104,
    "EU": 89
  }
} as const;
/** An approved dependency between two criteria: "from" has to be in place for "to" to work. */
export interface CriterionLink { from: string; to: string; reason: string; source: string }
export const LINKS: CriterionLink[] = [
 {
  "from": "1.1",
  "to": "1.3",
  "reason": "Policies carry authority only when a board or committee with an explicit AI remit has approved them; without that mandate, policy is one manager's preference.",
  "source": "UK Corporate Governance Code 2024"
 },
 {
  "from": "1.6",
  "to": "1.1",
  "reason": "A board cannot oversee what it has not been told is coming; tracking regulatory change is what keeps the board's AI agenda current.",
  "source": "UK Corporate Governance Code 2024"
 },
 {
  "from": "1.1",
  "to": "2.2",
  "reason": "Setting risk appetite is a board decision, so there has to be a board body that owns AI before appetite for AI risk can be defined.",
  "source": "UK Corporate Governance Code 2024; FRC Corporate Governance Code Guidance"
 },
 {
  "from": "1.1",
  "to": "2.5",
  "reason": "Accepting a risk needs sign-off from someone entitled to give it; the board mandate fixes where that authority sits.",
  "source": "NIST AI Risk Management Framework 1.0"
 },
 {
  "from": "4.6",
  "to": "1.1",
  "reason": "Board oversight is only as good as what the organisation can tell the board about what its AI does.",
  "source": "Bank of England SS1/23; ICO AI audit toolkit: governance and accountability"
 },
 {
  "from": "5.8",
  "to": "1.1",
  "reason": "The board shows it exercised oversight through the records kept; without the data trail, the mandate cannot be evidenced.",
  "source": "ICO AI audit toolkit: governance and accountability"
 },
 {
  "from": "1.1",
  "to": "6.8",
  "reason": "The board's declaration on material controls has to cover AI, which it can only do if AI is already within a board body's remit.",
  "source": "UK Corporate Governance Code 2024; Cyber Governance Code of Practice"
 },
 {
  "from": "1.1",
  "to": "7.4",
  "reason": "Workforce impact can only be considered and minuted before adoption if there is a board forum where AI adoption decisions are taken.",
  "source": "Companies Act 2006, s.248; UK Corporate Governance Code 2024"
 },
 {
  "from": "1.4",
  "to": "1.2",
  "reason": "A named owner can only be assigned to systems the organisation knows it has; the register is the list owners are assigned against.",
  "source": "Bank of England SS1/23; NAO, Use of artificial intelligence in government"
 },
 {
  "from": "1.2",
  "to": "2.1",
  "reason": "Someone has to be answerable for classifying each system and for the tier it is given.",
  "source": "Bank of England SS1/23; Bank of England and FCA, AI in UK financial services 2024"
 },
 {
  "from": "1.2",
  "to": "2.3",
  "reason": "An impact assessment needs a named person who commissions it and acts on its findings.",
  "source": "EU AI Act, Article 26; ICO guidance on AI and data protection (accountability)"
 },
 {
  "from": "1.2",
  "to": "2.4",
  "reason": "Deployer duties such as human oversight and monitoring must be assigned to named, competent people.",
  "source": "EU AI Act, Article 26"
 },
 {
  "from": "1.2",
  "to": "2.7",
  "reason": "Monitoring through a system's life lapses unless a named owner stays responsible after go-live.",
  "source": "Bank of England SS1/23; EU AI Act, Article 26"
 },
 {
  "from": "1.2",
  "to": "4.4",
  "reason": "A person contesting a decision needs a human with authority to review and change it, which is the escalation route this criterion defines.",
  "source": "UK GDPR, Article 22A"
 },
 {
  "from": "1.4",
  "to": "1.3",
  "reason": "Policies have to cover the AI actually in use; the register shows what that is, including tools bought in or embedded in other software.",
  "source": "DSIT AI Management Essentials; NIST AI RMF"
 },
 {
  "from": "1.6",
  "to": "1.3",
  "reason": "Policies stay current only if regulatory change is tracked and fed into them, including the staged application dates of the EU AI Act.",
  "source": "EU AI Act, Article 113"
 },
 {
  "from": "2.2",
  "to": "1.3",
  "reason": "Acceptable-use rules are the board's risk appetite written down for staff; without a stated appetite the policy has nothing to enforce.",
  "source": "UK Corporate Governance Code 2024; NIST AI RMF"
 },
 {
  "from": "1.3",
  "to": "2.6",
  "reason": "Suspending and reporting a misbehaving system relies on an escalation policy that says who decides and who is told.",
  "source": "NIST AI RMF; NIST Generative AI Profile"
 },
 {
  "from": "1.3",
  "to": "4.6",
  "reason": "Policy is what requires teams to record and disclose internally how they use AI.",
  "source": "DSIT AI Management Essentials"
 },
 {
  "from": "1.3",
  "to": "7.7",
  "reason": "People can only know what they may use if an approved acceptable-use policy exists and has reached them.",
  "source": "UK GDPR, Article 24; R (Ayinde) v London Borough of Haringey [2025] EWHC"
 },
 {
  "from": "1.4",
  "to": "2.8",
  "reason": "A proportionate approach has to be evidenced, and the register is the base record that evidence is built on.",
  "source": "UK GDPR, Article 30; Bank of England SS1/23"
 },
 {
  "from": "1.4",
  "to": "4.6",
  "reason": "Knowing what your AI does starts with knowing what AI you have.",
  "source": "Algorithmic Transparency Recording Standard; UK GDPR, Article 30"
 },
 {
  "from": "1.4",
  "to": "5.8",
  "reason": "The register is part of the records of processing; a data trail with systems missing from it is incomplete.",
  "source": "UK GDPR, Article 30"
 },
 {
  "from": "1.5",
  "to": "2.4",
  "reason": "Using a system as its provider instructs depends on obtaining those instructions and the right information at procurement.",
  "source": "EU AI Act, Article 25; Code of Practice for the Cyber Security of AI"
 },
 {
  "from": "1.5",
  "to": "3.7",
  "reason": "Checking a supplier's fairness claims is one part of vendor due diligence and needs the contractual right to test and audit.",
  "source": "Guidelines for AI procurement; ICO AI audit toolkit: contracts and third parties"
 },
 {
  "from": "1.5",
  "to": "4.5",
  "reason": "Explainability has to be written into requirements and contracts at purchase; it cannot be added to a bought-in system afterwards.",
  "source": "Guidelines for AI procurement; ICO AI audit toolkit: contracts and third parties"
 },
 {
  "from": "1.5",
  "to": "5.4",
  "reason": "A data protection impact assessment of a bought-in tool depends on information that only the vendor can supply, which due diligence must secure.",
  "source": "ICO, AI tools in recruitment: audit outcomes; R (Bridges) v Chief Constable of South Wales Police [2020] EWCA Civ 1058"
 },
 {
  "from": "1.5",
  "to": "5.7",
  "reason": "Honouring access and erasure requests where a vendor holds the data depends on the contract obliging the vendor to assist.",
  "source": "UK GDPR, Article 28; ICO AI audit toolkit: contracts and third parties"
 },
 {
  "from": "1.5",
  "to": "6.7",
  "reason": "Security assessment of models, APIs and suppliers is the security half of the same vendor due diligence.",
  "source": "PRA SS2/21; NCSC supply chain security guidance; Code of Practice for the Cyber Security of AI"
 },
 {
  "from": "2.3",
  "to": "1.7",
  "reason": "Independent review tests whether impact assessments were adequate; the Bridges judgment turned on one that was not.",
  "source": "R (Bridges) v Chief Constable of South Wales Police [2020] EWCA Civ 1058; DSIT Introduction to AI assurance"
 },
 {
  "from": "3.3",
  "to": "1.7",
  "reason": "Bias audit is one of the recognised assurance techniques; independent review relies on bias testing having been done and recorded.",
  "source": "DSIT Introduction to AI assurance"
 },
 {
  "from": "1.7",
  "to": "4.8",
  "reason": "Public claims about AI are credible when independently checked; assurance is what lets external reporting match technical reality.",
  "source": "DSIT Trusted third-party AI assurance roadmap"
 },
 {
  "from": "5.8",
  "to": "1.7",
  "reason": "An auditor or regulator can only review what has been recorded; assurance draws on the data trail.",
  "source": "Data Protection Act 2018, s.146"
 },
 {
  "from": "1.7",
  "to": "6.8",
  "reason": "The board's declaration on the effectiveness of material controls is stronger, and safer to sign, when it rests on independent assurance.",
  "source": "UK Corporate Governance Code 2024; DSIT Trusted third-party AI assurance roadmap"
 },
 {
  "from": "1.8",
  "to": "3.2",
  "reason": "Screening data for historical bias depends on documentation of where the data came from and how it was collected.",
  "source": "Gebru et al., Datasheets for Datasets; Algorithmic Transparency Recording Standard"
 },
 {
  "from": "1.8",
  "to": "7.4",
  "reason": "Showing that directors had regard to employees before adopting AI depends on the decision being minuted and the papers kept.",
  "source": "Companies Act 2006, ss.172, 248 and 414CZA"
 },
 {
  "from": "1.4",
  "to": "2.1",
  "reason": "Risk classification can only be complete if the register it works through is complete, including procured and embedded tools.",
  "source": "Bank of England SS1/23; NAO, Use of artificial intelligence in government; NIST AI RMF"
 },
 {
  "from": "1.8",
  "to": "5.8",
  "reason": "The evidence trail behind AI decisions and the data trail are two halves of the same record; a gap in one shows up in the other.",
  "source": "Algorithmic Transparency Recording Standard; Cobbe, Lee and Singh, Reviewable Automated Decision-Making"
 },
 {
  "from": "1.8",
  "to": "1.7",
  "reason": "Independent assurance reviews the documented evidence trail; without it there is nothing to audit.",
  "source": "Bank of England SS1/23; NIST AI RMF"
 },
 {
  "from": "1.1",
  "to": "1.2",
  "reason": "Named owners and escalation routes derive their authority from, and report to, the board body that holds the mandate.",
  "source": "Bank of England SS1/23; Artificial Intelligence Playbook for the UK Government"
 },
 {
  "from": "2.2",
  "to": "2.1",
  "reason": "Risk tiers mean something only against a stated appetite; the board's view of what it will not accept, including prohibited uses, sets where the tier boundaries sit.",
  "source": "EU AI Act, Article 5; Bank of England SS1/23; NIST AI RMF"
 },
 {
  "from": "2.1",
  "to": "2.3",
  "reason": "Classification is what triggers an impact assessment; a system that has not been tiered will not be recognised as needing one.",
  "source": "UK GDPR, Article 35; ICO, When do we need to do a DPIA?"
 },
 {
  "from": "2.7",
  "to": "2.1",
  "reason": "A tier given at adoption goes stale as the system and its use change; reassessment through the lifecycle keeps the classification true.",
  "source": "Bank of England SS1/23; NIST AI RMF"
 },
 {
  "from": "2.1",
  "to": "2.8",
  "reason": "Proportionality means scaling effort to risk, which is only possible once systems are sorted by tier.",
  "source": "Bank of England SS1/23; NAO, Use of artificial intelligence in government"
 },
 {
  "from": "2.1",
  "to": "3.4",
  "reason": "Restrictions on decisions using sensitive data can only be enforced where classification has flagged which systems use that data.",
  "source": "EU AI Act, Article 5; UK GDPR, Article 35"
 },
 {
  "from": "2.1",
  "to": "3.6",
  "reason": "An ethical review gate needs a rule for which deployments must pass through it; the risk tier supplies that rule.",
  "source": "NIST AI RMF; ICO, When do we need to do a DPIA?"
 },
 {
  "from": "2.2",
  "to": "2.5",
  "reason": "Deciding to mitigate, transfer or accept a risk is a judgement against appetite; without a stated appetite, acceptance has no test.",
  "source": "UK Corporate Governance Code 2024; NIST AI RMF"
 },
 {
  "from": "2.2",
  "to": "6.8",
  "reason": "The board's declaration on material controls has to say which AI risks are material, which follows from the appetite it has set.",
  "source": "UK Corporate Governance Code 2024; FRC Corporate Governance Code Guidance"
 },
 {
  "from": "3.1",
  "to": "2.3",
  "reason": "A rights impact assessment has to say who could be affected and how; the mapping of protected characteristics against AI uses is that input.",
  "source": "Equality Act 2010, s.149; EU AI Act, Article 27; R (Bridges) [2020] EWCA Civ 1058"
 },
 {
  "from": "2.3",
  "to": "3.6",
  "reason": "The ethical review gate decides on evidence, and the impact assessment is the main evidence put before it.",
  "source": "UK GDPR, Article 35; EU AI Act, Article 27; Ada Lovelace Institute, Algorithmic impact assessment"
 },
 {
  "from": "5.4",
  "to": "2.3",
  "reason": "The data protection impact assessment is the established discipline that wider rights assessments build on; where it is weak, the broader assessment will be too.",
  "source": "UK GDPR, Article 35; EU AI Act, Article 27; ICO, What is a DPIA?"
 },
 {
  "from": "2.3",
  "to": "5.8",
  "reason": "A completed impact assessment is one of the core records an organisation is expected to produce on request.",
  "source": "ICO guidance on AI and data protection (accountability); R (Bridges) [2020] EWCA Civ 1058"
 },
 {
  "from": "2.3",
  "to": "7.5",
  "reason": "Telling workers and their representatives what a system will do to them draws on what the impact assessment found.",
  "source": "UK GDPR, Article 35; EU AI Act, Article 26"
 },
 {
  "from": "2.4",
  "to": "2.5",
  "reason": "Operational controls such as input checks and monitoring are the mitigations in practice; a treatment plan with no working controls is only a document.",
  "source": "NIST AI RMF; Post Office Horizon IT Inquiry, Volume 1"
 },
 {
  "from": "2.8",
  "to": "2.4",
  "reason": "How much control a system needs should follow from a documented view of its risk; proportionality sets the depth of operational control.",
  "source": "Bank of England SS1/23; ICO guidance on AI and data protection (accountability)"
 },
 {
  "from": "4.5",
  "to": "2.4",
  "reason": "A deployer can only follow the provider's instructions and interpret outputs if the system came with that information, which is what explainability by design secures.",
  "source": "EU AI Act, Article 13"
 },
 {
  "from": "2.4",
  "to": "5.8",
  "reason": "Keeping the logs a system generates is a deployer control; those logs are a large part of the data trail.",
  "source": "EU AI Act, Article 12; UK GDPR, Article 5"
 },
 {
  "from": "6.3",
  "to": "2.4",
  "reason": "Monitoring and log retention can be trusted only if access to models, prompts and pipelines is controlled and changes are logged.",
  "source": "Code of Practice for the Cyber Security of AI; Data Protection Act 2018, s.62; ETSI TS 104 223"
 },
 {
  "from": "6.7",
  "to": "2.4",
  "reason": "Operating a system safely assumes its model, API and vendor dependencies have been security-assessed.",
  "source": "EU AI Act, Article 25; Code of Practice for the Cyber Security of AI"
 },
 {
  "from": "7.1",
  "to": "2.4",
  "reason": "Controls are operated by people; staff who cannot use AI competently will not apply provider instructions or spot bad inputs.",
  "source": "R (Ayinde) v London Borough of Haringey [2025] EWHC 1383; Code of Practice for the Cyber Security of AI"
 },
 {
  "from": "2.7",
  "to": "2.5",
  "reason": "A decision to accept or mitigate a risk holds only while circumstances hold; monitoring is what shows when the treatment needs revisiting.",
  "source": "HM Treasury Orange Book; EU AI Act, Article 9"
 },
 {
  "from": "4.5",
  "to": "2.5",
  "reason": "A risk cannot be mitigated if nobody can see why the system behaves as it does; explainability is a precondition for effective treatment.",
  "source": "NIST AI RMF; ICO guidance on AI and data protection (accountability)"
 },
 {
  "from": "5.4",
  "to": "2.5",
  "reason": "The impact assessment identifies the measures to reduce risk, and where high risk remains it requires consultation with the regulator before going ahead.",
  "source": "UK GDPR, Article 36; ICO, How do we do a DPIA?"
 },
 {
  "from": "2.5",
  "to": "6.8",
  "reason": "The board can declare its controls effective only if identified risks have in fact been treated and signed off.",
  "source": "UK Corporate Governance Code 2024; Post Office Horizon IT Inquiry, Volume 1"
 },
 {
  "from": "2.7",
  "to": "2.6",
  "reason": "A misbehaving system has to be detected before it can be suspended; ongoing monitoring is the detection.",
  "source": "EU AI Act, Article 26; NIST AI RMF"
 },
 {
  "from": "2.6",
  "to": "6.5",
  "reason": "Suspending an AI system and reporting on time works when AI failure is already routed into the organisation's rehearsed incident process.",
  "source": "EU AI Act, Article 73; UK GDPR, Article 33; NIS Regulations 2018, reg. 11"
 },
 {
  "from": "7.2",
  "to": "2.6",
  "reason": "Suspension is a human decision; it happens only if the people overseeing the system are trained and have the authority to stop it.",
  "source": "EU AI Act, Article 26; NIST Generative AI Profile"
 },
 {
  "from": "3.3",
  "to": "2.7",
  "reason": "Testing outcomes for disparate impact is one of the checks lifecycle monitoring has to repeat, because bias can emerge after go-live.",
  "source": "EU AI Act, Article 9; ICO, AI tools in recruitment: audit outcomes"
 },
 {
  "from": "2.7",
  "to": "5.4",
  "reason": "An impact assessment is meant to be kept under review; monitoring is what triggers its update when the processing or the risk changes.",
  "source": "UK GDPR, Article 35; ICO, How do we do a DPIA?"
 },
 {
  "from": "5.6",
  "to": "2.7",
  "reason": "Monitoring for drift and accuracy depends on knowing the data going in is relevant and representative; poor data quality hides or mimics model failure.",
  "source": "ICO guidance on AI and data protection (accuracy); Bank of England SS1/23"
 },
 {
  "from": "4.5",
  "to": "2.8",
  "reason": "Evidencing a proportionate approach relies on documentation of what each system is for and how it behaves, which explainability requirements produce.",
  "source": "Mitchell et al., Model Cards for Model Reporting; Bank of England SS1/23"
 },
 {
  "from": "4.6",
  "to": "2.8",
  "reason": "An organisation cannot show its approach is scaled to its context unless it knows internally what its AI does.",
  "source": "UK GDPR, Article 30; Raji et al., Closing the AI Accountability Gap"
 },
 {
  "from": "2.8",
  "to": "5.8",
  "reason": "The documentation that evidences a proportionate risk approach is itself part of the record the data trail must hold.",
  "source": "UK GDPR, Article 30; ICO guidance on AI and data protection (accountability)"
 },
 {
  "from": "2.3",
  "to": "2.5",
  "reason": "Risk treatment acts on what impact assessments find; without assessments, treatment addresses only the risks someone happened to notice.",
  "source": "ICO guidance on AI and data protection (accountability)"
 },
 {
  "from": "2.1",
  "to": "2.4",
  "reason": "Which deployer controls apply depends on the tier; high-risk systems carry duties that lower tiers do not.",
  "source": "Bank of England SS1/23; NIST AI RMF"
 },
 {
  "from": "3.1",
  "to": "3.2",
  "reason": "Screening data for bias needs to know which characteristics are at stake in each use, including proxies for them; the mapping supplies that list.",
  "source": "Equality Act 2010, s.19; ICO guidance on AI and data protection (fairness, bias and discrimination)"
 },
 {
  "from": "3.1",
  "to": "3.3",
  "reason": "Testing outcomes for disparate impact has to be run across specific groups; the mapping of protected characteristics says which.",
  "source": "Equality Act 2010, s.19; R (Bridges) [2020] EWCA Civ 1058; CDEI Review into bias in algorithmic decision-making"
 },
 {
  "from": "3.1",
  "to": "3.7",
  "reason": "The organisation stays liable for discrimination by a tool it bought, so it has to know which characteristics to press the supplier on.",
  "source": "Equality Act 2010, s.109; DSIT Responsible AI in Recruitment"
 },
 {
  "from": "3.2",
  "to": "3.3",
  "reason": "Outcome testing finds bias after the event; it is interpretable only when the data feeding the system has been screened first, and each informs the other.",
  "source": "ICO guidance on AI and data protection, Annex A; FCA Research Note on bias in supervised machine learning"
 },
 {
  "from": "3.4",
  "to": "3.2",
  "reason": "Checking data for bias usually means handling sensitive characteristics, which is lawful only within the special-category controls.",
  "source": "UK GDPR, Article 9; CDEI, Enabling responsible access to demographic data"
 },
 {
  "from": "3.2",
  "to": "3.7",
  "reason": "A supplier's fairness claim can only be verified by someone who understands what bias in data looks like and asks to see the supplier's evidence on it.",
  "source": "ICO, AI tools in recruitment: audit outcomes; DSIT Responsible AI in Recruitment"
 },
 {
  "from": "5.5",
  "to": "3.2",
  "reason": "Using sensitive data to detect and correct bias depends on the narrow legal exceptions being correctly applied and documented.",
  "source": "UK GDPR, Article 9; Data Protection Act 2018, Schedule 1, Part 4; van Bekkum and Zuiderveen Borgesius (2023)"
 },
 {
  "from": "5.6",
  "to": "3.2",
  "reason": "Data that is unrepresentative or excessive is a main source of bias; data quality discipline is where screening starts.",
  "source": "EU AI Act, Article 10; ICO, AI tools in recruitment: audit outcomes"
 },
 {
  "from": "3.3",
  "to": "3.7",
  "reason": "Verifying a vendor's fairness claim means testing outcomes yourself or examining the vendor's test results, so in-house bias testing capability comes first.",
  "source": "NYC Local Law 144 guidance; Raghavan et al., Mitigating Bias in Algorithmic Hiring"
 },
 {
  "from": "3.5",
  "to": "3.4",
  "reason": "Where significant decisions use sensitive data, the law restricts solely automated decisions; meaningful human review is the control that keeps a decision outside that restriction.",
  "source": "UK GDPR, Articles 22A and 22C; Data (Use and Access) Act 2025, s.80"
 },
 {
  "from": "5.1",
  "to": "3.4",
  "reason": "Restrictions on sensitive-data automated decisions can be enforced only once the organisation has identified which of its decisions are automated and significant.",
  "source": "UK GDPR, Article 22A; Data (Use and Access) Act 2025 Explanatory Notes"
 },
 {
  "from": "3.5",
  "to": "4.4",
  "reason": "A person contesting a decision is entitled to human intervention; that right is empty unless the human review is meaningful.",
  "source": "UK GDPR, Article 22C; Green, The Flaws of Policies Requiring Human Oversight (2022)"
 },
 {
  "from": "4.7",
  "to": "3.5",
  "reason": "People can ask for human review only if they have been told an automated decision was made about them.",
  "source": "UK GDPR, Article 22C; ICO, AI tools in recruitment: audit outcomes"
 },
 {
  "from": "5.1",
  "to": "3.5",
  "reason": "Whether a decision counts as solely automated turns on the quality of human involvement, so scoping and human review have to be worked out together, starting with knowing which decisions are in scope.",
  "source": "UK GDPR, Article 22A; ICO draft guidance on automated decision-making"
 },
 {
  "from": "3.5",
  "to": "5.2",
  "reason": "Human intervention is one of the statutory safeguards; the safeguards are not implemented unless the review is real.",
  "source": "UK GDPR, Article 22C; ICO AI audit toolkit: human review"
 },
 {
  "from": "7.2",
  "to": "3.5",
  "reason": "Review is meaningful only when reviewers are trained, have time and can overrule the system; research shows untrained reviewers defer to it.",
  "source": "ICO AI audit toolkit: human review; Alon-Barkat and Busuioc (2022)"
 },
 {
  "from": "7.3",
  "to": "3.5",
  "reason": "Reviewers can only intervene where the system and the process were designed to let them see, question and override outputs.",
  "source": "EU AI Act, Article 14; UK GDPR, Article 22C"
 },
 {
  "from": "5.4",
  "to": "3.6",
  "reason": "The ethical review gate needs a triggering process and written evidence; the data protection impact assessment already provides both and can require a deployment to pause.",
  "source": "UK GDPR, Articles 35 and 36; ICO, When do we need to do a DPIA?"
 },
 {
  "from": "4.5",
  "to": "3.7",
  "reason": "A supplier's fairness claims can be checked only if the contract secured enough information about how the system works.",
  "source": "Guidelines for AI procurement; EU AI Act, Article 13; ICO AI audit toolkit: contracts and third parties"
 },
 {
  "from": "4.1",
  "to": "3.8",
  "reason": "People can seek redress only if they know AI was involved in what happened to them.",
  "source": "OECD AI Principles, 1.3; UNESCO Recommendation on the Ethics of AI"
 },
 {
  "from": "4.3",
  "to": "3.8",
  "reason": "Putting an unfair decision right starts with being able to explain that decision; without an explanation neither side can see what went wrong.",
  "source": "EU AI Act, Article 86; UK GDPR, Article 22C"
 },
 {
  "from": "4.4",
  "to": "3.8",
  "reason": "Contesting a decision is the route by which unfair treatment reaches remediation; with no working route, harm stays undiscovered.",
  "source": "UK GDPR, Article 22C; Post Office Horizon IT Inquiry, Volume 1"
 },
 {
  "from": "4.7",
  "to": "3.8",
  "reason": "Redress depends on affected people being notified that a significant automated decision was made.",
  "source": "UK GDPR, Article 22C; ICO draft guidance on ADM safeguards"
 },
 {
  "from": "5.2",
  "to": "3.8",
  "reason": "The statutory safeguards (information, representations, human intervention, contest) are the machinery redress runs on.",
  "source": "UK GDPR, Article 22C; Lyons et al., Conceptualising Contestability (2021)"
 },
 {
  "from": "3.6",
  "to": "3.8",
  "reason": "The body that can stop a deployment on ethical grounds is also the natural owner of decisions to withdraw a system and put harm right.",
  "source": "UNESCO Recommendation on the Ethics of Artificial Intelligence"
 },
 {
  "from": "4.1",
  "to": "4.2",
  "reason": "Telling people they are dealing with AI and marking AI-generated content are two duties under the same provision; an organisation without a disclosure standard has no basis for a marking one.",
  "source": "EU AI Act, Article 50"
 },
 {
  "from": "4.1",
  "to": "4.4",
  "reason": "People can only challenge an AI-influenced outcome if they were told AI was involved.",
  "source": "OECD AI Principles, 1.3; UNESCO Recommendation on the Ethics of AI"
 },
 {
  "from": "4.3",
  "to": "4.4",
  "reason": "A person cannot make meaningful representations against a decision they have not had explained to them.",
  "source": "UK GDPR, Article 22C; ICO, Explaining decisions made with AI, Part 1"
 },
 {
  "from": "4.5",
  "to": "4.3",
  "reason": "An explanation of a specific decision can be given only if the system was bought or built to produce one.",
  "source": "ICO, Explaining decisions made with AI, Part 3; Bank of England and FCA, AI in UK financial services 2024"
 },
 {
  "from": "4.7",
  "to": "4.3",
  "reason": "The explanation is owed to people who have been notified; notification is the event that starts the explanation duty.",
  "source": "UK GDPR, Article 22C; ICO draft guidance on ADM safeguards"
 },
 {
  "from": "4.3",
  "to": "5.2",
  "reason": "Giving information about a decision is one of the statutory safeguards; they are not implemented without a working explanation process.",
  "source": "UK GDPR, Article 22C; EU AI Act, Article 86"
 },
 {
  "from": "4.3",
  "to": "7.3",
  "reason": "The person overseeing a system needs the same decision-level explanation to judge whether to accept or override an output.",
  "source": "DSIT Ethics, Transparency and Accountability Framework for Automated Decision-Making"
 },
 {
  "from": "4.7",
  "to": "4.4",
  "reason": "The right to contest begins with being told a significant automated decision has been made.",
  "source": "UK GDPR, Article 22C; ICO draft guidance on ADM safeguards"
 },
 {
  "from": "4.4",
  "to": "5.2",
  "reason": "The ability to make representations, obtain human intervention and contest are three of the four statutory safeguards.",
  "source": "UK GDPR, Article 22C; Kaminski and Urban, The Right to Contest AI (2021)"
 },
 {
  "from": "4.5",
  "to": "7.3",
  "reason": "Human oversight can be designed in only where the system exposes enough of its reasoning for a person to question it.",
  "source": "UK GDPR, Article 25; NIST AI RMF"
 },
 {
  "from": "4.6",
  "to": "5.8",
  "reason": "The data trail records what the organisation knows about its AI; it cannot evidence what has never been established internally.",
  "source": "UK GDPR, Articles 5 and 30; ICO AI audit toolkit: governance and accountability"
 },
 {
  "from": "7.7",
  "to": "4.6",
  "reason": "An organisation does not know what its AI does while staff are using tools it has not sanctioned and cannot see.",
  "source": "DSIT AI Adoption Research; University of Melbourne and KPMG, Trust, attitudes and use of AI 2025"
 },
 {
  "from": "4.7",
  "to": "5.2",
  "reason": "Telling people about a decision is the first of the statutory safeguards and the one the others depend on.",
  "source": "UK GDPR, Article 22C; Data Protection Act 2018, s.50C"
 },
 {
  "from": "4.8",
  "to": "8.8",
  "reason": "Using governance credentials to win business is safe only if the public claims are accurate; misleading claims to business customers are unlawful.",
  "source": "Business Protection from Misleading Marketing Regulations 2008, reg. 3"
 },
 {
  "from": "4.6",
  "to": "4.8",
  "reason": "Public claims about AI can match technical reality only if the organisation itself knows what its AI does.",
  "source": "UK Corporate Governance Code 2024"
 },
 {
  "from": "7.2",
  "to": "5.1",
  "reason": "Whether a decision is solely automated depends on what the human reviewer really does; scoping is wrong if it assumes oversight that is nominal.",
  "source": "ICO guidance on automated decision-making; Green (2022); Alon-Barkat and Busuioc (2022)"
 },
 {
  "from": "5.3",
  "to": "5.5",
  "reason": "Sensitive data needs a lawful basis and then a further condition on top; the second cannot be met where the first has not been established.",
  "source": "ICO guidance on AI and data protection (lawfulness); ICO Enforcement Notice, Serco Leisure (2024); Information Commissioner v Clearview AI [2025] UKUT 319 (AAC)"
 },
 {
  "from": "5.1",
  "to": "5.2",
  "reason": "Safeguards attach to significant automated decisions; they can only be put in place for decisions the organisation has identified as in scope.",
  "source": "ICO guidance on automated decision-making; Article 29 Working Party Guidelines on automated decision-making and profiling"
 },
 {
  "from": "5.4",
  "to": "5.8",
  "reason": "The completed impact assessment, and what was done about its findings, is a core part of the data trail.",
  "source": "ICO guidance on AI and data protection (accountability); R (Bridges) [2020] EWCA Civ 1058"
 },
 {
  "from": "5.6",
  "to": "5.4",
  "reason": "An impact assessment has to judge whether the data is necessary and proportionate, which rests on data quality and minimisation having been examined.",
  "source": "ICO, AI tools in recruitment: audit outcomes"
 },
 {
  "from": "6.1",
  "to": "6.2",
  "reason": "Secure development and procurement requirements are written against known threats; a team unaware of AI-specific attacks will not ask for the right protections.",
  "source": "Code of Practice for the Cyber Security of AI; UK GDPR, Article 32"
 },
 {
  "from": "6.1",
  "to": "6.3",
  "reason": "Deciding who may touch models, prompts and pipelines follows from understanding how they can be attacked or misused.",
  "source": "Code of Practice for the Cyber Security of AI; ICO guidance on AI and data protection (security)"
 },
 {
  "from": "6.1",
  "to": "6.6",
  "reason": "Recovery plans have to cover the ways AI fails or is attacked, which only threat awareness identifies.",
  "source": "Code of Practice for the Cyber Security of AI; Bank of England, Financial Stability in Focus: AI (2025)"
 },
 {
  "from": "6.2",
  "to": "6.3",
  "reason": "Access and change controls are far easier to enforce on systems built or bought with them specified from the start.",
  "source": "NCSC Guidelines for secure AI system development; ETSI TS 104 223"
 },
 {
  "from": "6.2",
  "to": "6.4",
  "reason": "The ability to contain or switch off a system has to be designed in or contracted for; it cannot be relied on if it was never built.",
  "source": "Code of Practice for the Cyber Security of AI; Implementation Guide"
 },
 {
  "from": "6.2",
  "to": "6.7",
  "reason": "Supply-chain security is the same secure-by-design discipline applied to models, APIs and vendors brought in from outside.",
  "source": "Code of Practice for the Cyber Security of AI; PRA SS2/21; Gu et al., BadNets (2017)"
 },
 {
  "from": "6.3",
  "to": "6.4",
  "reason": "A kill-switch is only as dependable as the control over who can use it and who can change the system around it.",
  "source": "Code of Practice for the Cyber Security of AI; NCSC, Managing the cyber risk of agentic AI"
 },
 {
  "from": "6.7",
  "to": "6.5",
  "reason": "Many AI incidents start at a supplier; response works only if dependencies are known and vendors are bound to notify and co-operate.",
  "source": "Code of Practice for the Cyber Security of AI; Cyber Governance Code of Practice"
 },
 {
  "from": "6.6",
  "to": "6.8",
  "reason": "The board cannot declare its controls effective for AI without evidence that critical services can withstand and recover from AI failure.",
  "source": "FCA Handbook, SYSC 15A; Cyber security breaches survey 2025/2026"
 },
 {
  "from": "7.8",
  "to": "6.6",
  "reason": "Falling back to manual operation when AI fails depends on people still having the skills to do the work themselves.",
  "source": "CAA Paper 2004/10, Flight Crew Reliance on Automation"
 },
 {
  "from": "7.4",
  "to": "7.5",
  "reason": "Workers and their representatives can only be told what a system will mean for them once its impact on their jobs has been assessed.",
  "source": "EU AI Act, Article 26; UK GDPR, Article 35"
 },
 {
  "from": "7.4",
  "to": "7.6",
  "reason": "A strategy of augmenting people before replacing them needs the role-by-role evidence that an impact assessment produces.",
  "source": "Companies Act 2006, s.172; TULRCA 1992, s.188; DSIT assessment of AI and the UK labour market (2026)"
 },
 {
  "from": "7.6",
  "to": "7.8",
  "reason": "Skills are sustained when the strategy keeps people doing meaningful parts of the work; a replacement-first approach lets them lapse.",
  "source": "OECD AI Principles, 2.4; World Economic Forum, Future of Jobs Report 2025"
 },
 {
  "from": "8.1",
  "to": "8.2",
  "reason": "Which sustainability data an organisation must hold is set by what its customers, lenders and reporting partners will ask of it.",
  "source": "Niemann et al., Data Requests in Value Chains (2025); OECD, Fostering convergence in SME sustainability reporting"
 },
 {
  "from": "8.1",
  "to": "8.3",
  "reason": "How far readiness needs to go follows from the organisation's position in other firms' value chains and public contracts.",
  "source": "PPN 006; PRA SS5/25"
 },
 {
  "from": "8.1",
  "to": "8.4",
  "reason": "Knowing where the legal limit on value-chain requests sits matters only once the organisation knows who is asking and in what capacity.",
  "source": "Directive (EU) 2026/470; Commission Delegated Regulation (EU) 2026/1563"
 },
 {
  "from": "8.2",
  "to": "8.3",
  "reason": "Wider readiness on strategy, targets and climate risk is built on top of the basic data set; without it the rest is assertion.",
  "source": "EFRAG VSME standard; Commission Delegated Regulation (EU) 2026/1560"
 },
 {
  "from": "8.2",
  "to": "8.4",
  "reason": "The limit on what larger partners may request is defined by reference to the voluntary standard's data set, so having that data is how the protection is used.",
  "source": "Commission Recommendation (EU) 2025/1710; Commission Delegated Regulation (EU) 2026/1560"
 },
 {
  "from": "8.4",
  "to": "8.3",
  "reason": "Knowing what cannot be demanded lets the organisation aim its readiness at what is warranted, not at every request it receives.",
  "source": "Commission Delegated Regulation (EU) 2026/1560; PPN 006"
 },
 {
  "from": "8.5",
  "to": "8.3",
  "reason": "AI use adds to energy use and purchased-services emissions, so a full picture of readiness has to include the AI footprint.",
  "source": "Greenhouse Gas Protocol Corporate Value Chain (Scope 3) Standard"
 },
 {
  "from": "8.6",
  "to": "8.3",
  "reason": "Readiness claims rest on the numbers behind them; weak data quality undermines every disclosure built on it.",
  "source": "EFRAG VSME standard; Klaaßen and Stoll, Harmonizing corporate carbon footprints (2021)"
 },
 {
  "from": "8.7",
  "to": "8.3",
  "reason": "Readiness is sustained when someone senior is accountable and the board sees progress; disclosure frameworks ask for that governance first.",
  "source": "UK SRS S2; Companies Act 2006, s.414CB; FRC Thematic Review of climate-related disclosures (2025)"
 },
 {
  "from": "8.4",
  "to": "8.8",
  "reason": "Sustainability credentials win contracts when the organisation knows what buyers can legitimately require and offers that confidently.",
  "source": "PPN 006; Procurement Act 2023, s.12"
 },
 {
  "from": "8.6",
  "to": "8.5",
  "reason": "A figure for AI's environmental footprint is credible only if it is measured to the same standard as the rest of the organisation's energy and carbon data.",
  "source": "Greenhouse Gas Protocol Scope 3 Standard; Environmental Reporting Guidelines (SECR)"
 }
];
/** The same links as [from, to, weight] for the landing-page map. */
export const CRITERION_LINKS: [string, string, number][] = LINKS.map((l) => [l.from, l.to, 3]);


/** Briefing metadata for a criterion id, or undefined if none exists. */
export function articleFor(criterionId: string): ArticleMeta | undefined {
  return ARTICLE_META.find((a) => a.id === criterionId);
}

/** Glossary terms grouped by initial letter, for the A–Z index. */
export function glossaryGroups(): { letter: string; entries: GlossaryMeta[] }[] {
  const map = new Map<string, GlossaryMeta[]>();
  for (const e of GLOSSARY_META) {
    const letter = e.term[0].toUpperCase();
    const key = /[A-Z]/.test(letter) ? letter : "#";
    if (!map.has(key)) map.set(key, []);
    map.get(key)!.push(e);
  }
  return [...map.entries()].sort((a, b) => a[0].localeCompare(b[0])).map(([letter, entries]) => ({ letter, entries }));
}
