// src/lib/glossary.ts
// The glossary: plain-English definitions of every term of art in the
// framework and briefings, each linked back to the criteria where it matters.
// STATUS: DRAFT copy — awaiting Andy's sign-off. UK English, no jargon
// defining jargon.

export interface GlossaryEntry {
  term: string;
  def: string;        // two-sentence plain-English definition
  source?: string;    // the instrument or context it comes from
  related?: string[]; // criterion ids, e.g. ["2.3", "5.4"]
}

export const GLOSSARY: GlossaryEntry[] = [
  { term: "8×8 framework", def: "Principled Futures' assessment structure: eight governance domains, each with eight criteria, scored 0–4 against defined maturity bands. Sixty-four questions that together describe how well an organisation governs its AI and ESG position.", source: "Principled Futures", related: ["1.1"] },
  { term: "Accountability file", def: "One maintained folder per AI system holding its classification, impact assessments, approvals, testing records, incidents and reviews. The test is whether it can be produced in an afternoon, from known locations, by someone other than its author.", source: "UK GDPR Article 5(2)", related: ["1.8", "5.8"] },
  { term: "Accountability rings", def: "The three circles of people around the telemetry measures: those who run AI daily, those who set the rules, and the outside eyes who check both. Every measure belongs to one named person in one ring.", source: "Principled Futures telemetry", related: ["7.2"] },
  { term: "Adversarial input", def: "An input deliberately crafted to look normal to humans while making an AI system misbehave — flipping a classification or slipping a filter. One of the attack types unique to AI that conventional security testing does not cover.", source: "EU AI Act robustness requirements", related: ["6.1"] },
  { term: "AI Act (EU)", def: "The European Union's AI regulation, phasing in from 2025 to 2028: prohibited practices, transparency duties from August 2026, and full high-risk obligations from late 2027. It reaches UK organisations whose systems or outputs touch people in the EU.", source: "EU Regulation 2024/1689", related: ["2.1", "1.6"] },
  { term: "AI literacy duty", def: "Article 4 of the EU AI Act: organisations must support a sufficient level of AI literacy in staff and anyone using AI on their behalf, applicable since February 2025 with enforcement from August 2026. An effort obligation — but one that fails where no effort can be evidenced.", source: "EU AI Act Article 4", related: ["7.1"] },
  { term: "AI register", def: "A single maintained record of every AI system in use — including AI embedded in procured software — with each system's purpose, data, risk tier and named owner. The starting point of governance: you cannot govern what you have not listed.", source: "Principled Futures framework", related: ["1.4", "4.6"] },
  { term: "AI-washing", def: "Overstating what your AI does, how autonomous it is, or how well it is governed — in marketing, bids or investor material. Now a named enforcement concern, and the easiest audit anyone will ever run against your own records.", related: ["4.8"] },
  { term: "Article 22B / 22C (UK GDPR)", def: "The UK's rebuilt automated-decision rules, in force since February 2026. Article 22B keeps a hard default prohibition on significant automated decisions using special-category data; Article 22C sets the four safeguards for every other significant automated decision.", source: "Data (Use and Access) Act 2025", related: ["3.4", "5.1", "5.2"] },
  { term: "Article 26 (EU AI Act)", def: "The deployer-obligations article: use high-risk AI per the provider's instructions, assign competent human oversight, keep input data relevant, monitor operation, retain logs for at least six months, and inform workers and affected people. Where most SMEs' AI Act duties actually live.", source: "EU AI Act Article 26", related: ["2.4"] },
  { term: "Article 50 (EU AI Act)", def: "The transparency article, live from 2 August 2026: people must be told when they are interacting with AI, and generative systems must mark synthetic content machine-readably. The first AI Act duty most organisations will meet in practice.", source: "EU AI Act Article 50", related: ["4.1", "4.2"] },
  { term: "Assessment notice", def: "The ICO's power to compel an organisation to submit to an audit or produce reports on its data processing. The reason the accountability file needs to exist before the letter arrives, not after.", source: "UK Data Protection Act 2018", related: ["1.7", "5.8"] },
  { term: "ATRS", def: "The Algorithmic Transparency Recording Standard: the UK government's template for documenting how public-sector algorithms work, mandatory for central departments. A ready-made model for what \"documented enough\" looks like in the private sector too.", source: "UK Government / DSIT", related: ["4.5"] },
  { term: "Augmentation-first", def: "The adoption strategy in which AI's purpose is extending what your existing workforce can do, rather than replacing it. Measured in throughput and quality rather than headcount reduction — the strategy with the better failure profile and the better story.", source: "Principled Futures framework", related: ["7.6"] },
  { term: "Automation bias", def: "The documented human tendency to defer to machine output, strongest exactly when the machine is usually right. The reason oversight has to be designed and measured, not just staffed.", related: ["7.3", "3.5"] },
  { term: "Balancing test", def: "The documented weighing exercise required when relying on legitimate interests as a lawful basis: your interest, the necessity of the processing, and the impact on the individuals concerned. A recital is not a test; the test is the writing-down.", source: "UK GDPR Article 6(1)(f)", related: ["5.3"] },
  { term: "Basic Module (VSME)", def: "Disclosures B1 to B11 of the voluntary SME sustainability standard: company profile, energy, emissions, workforce, safety, pay and conduct. The standardised data set that answers most customer and bank questionnaires — assembled once, reused everywhere.", source: "EFRAG VSME", related: ["8.2"] },
  { term: "Bias carve-out", def: "The explicit lawful route, established by the Omnibus package, for processing personal data to detect and correct bias in AI systems. Permission for a purpose — use it deliberately, record the basis, and confine it to fairness work.", source: "EU Digital Omnibus", related: ["3.2"] },
  { term: "Breach (telemetry)", def: "A metric that has crossed its threshold — the red state in the register, escalating to the people who own the response. Distinct from a data breach, which is a security incident involving personal data.", source: "Principled Futures telemetry", related: ["2.2"] },
  { term: "Comprehensive Module (VSME)", def: "Disclosures C1 to C9 of the voluntary SME standard: strategy, targets, climate risks, human rights and Scope 3 emissions. The fuller data set worth building for the lenders and flagship clients whose business justifies it.", source: "EFRAG VSME", related: ["8.3"] },
  { term: "Concentration risk", def: "Multiple critical processes resting on one vendor, one model family or one integration point — individually sensible choices compounding into a single point of failure. Named, priced and exit-planned in mature estates.", related: ["6.6", "6.7"] },
  { term: "Containment", def: "The designed, rehearsed capability to stop an AI system quickly: defined triggers, authorised people, dual authorisation for drastic action, a tested mechanism and a rollback plan. For systems that act autonomously, the licence for everything else.", source: "Principled Futures framework", related: ["6.4"] },
  { term: "Contestability", def: "A person's practical ability to challenge an automated decision and obtain a fresh look with a possible different outcome. One of the DUAA's four safeguards — and a process that never changes an outcome is not one.", source: "DUAA / UK GDPR Article 22C", related: ["4.4"] },
  { term: "CSRD", def: "The EU's Corporate Sustainability Reporting Directive. Since the Omnibus reforms its mandatory scope starts at 1,000 employees and €450 million turnover — but in-scope companies must report on their value chains, which is how its questions reach smaller suppliers.", source: "EU Directive, as amended by Omnibus I", related: ["8.1"] },
  { term: "Data minimisation", def: "The principle that you process no more personal data than the purpose needs. AI's appetite for context makes \"feed it everything\" the path of least resistance — and every unnecessary field a compliance exposure, a bias vector and a breach multiplier.", source: "UK GDPR Article 5(1)(c)", related: ["5.6"] },
  { term: "Data poisoning", def: "Corrupting an AI system upstream by manipulating its training or reference data so it learns the attacker's preferred behaviour. Typically discovered, if at all, long after the damage compounds.", source: "NCSC secure AI guidance", related: ["6.1"] },
  { term: "Deepfake", def: "AI-generated or manipulated content that convincingly depicts real people, places or events. Publishing one triggers disclosure duties under the AI Act, with narrow carve-outs for evidently artistic or satirical work.", source: "EU AI Act Article 50", related: ["4.2"] },
  { term: "Deployer", def: "An organisation using an AI system under its own authority — as opposed to the provider who built it. Most SMEs are deployers, and deployer duties (instructions, oversight, input data, monitoring, logs) are where their obligations concentrate.", source: "EU AI Act", related: ["2.4"] },
  { term: "Disparate impact", def: "A pattern in which a system's outcomes differ substantially across groups sharing a protected characteristic, regardless of intent. Measured by comparing selection or approval rates — the number that turns fairness from assertion into evidence.", source: "Equality law practice", related: ["3.3"] },
  { term: "DPIA", def: "A Data Protection Impact Assessment: the structured, documented assessment required before processing likely to be high-risk to individuals — which automated decision-making about people almost always is. Done at the right moment, the cheapest design review your AI will get.", source: "UK GDPR Article 35", related: ["2.3", "5.4"] },
  { term: "DSIT", def: "The UK's Department for Science, Innovation and Technology — home of the government's AI policy, the central AI risk function, and the guidance ecosystem (including the ATRS and assurance portfolio) this framework draws on.", source: "UK Government" },
  { term: "Dual authorisation", def: "The two-key discipline for drastic actions on consequential systems: suspension requires two authorised people, preventing both rogue shutdown and rogue hesitation. Standard practice for kill-switch design.", related: ["6.4"] },
  { term: "DUAA", def: "The Data (Use and Access) Act 2025: the UK statute that rebuilt the automated-decision rules around permission-plus-safeguards, created the recognised-legitimate-interests basis, and amended the UK GDPR. In force for ADM purposes since February 2026.", source: "UK statute", related: ["5.1", "5.2"] },
  { term: "EFRAG", def: "The European Financial Reporting Advisory Group — author of the EU's sustainability reporting standards, including the voluntary SME standard (VSME) this framework's ESG domain is built around.", source: "EU standard-setter", related: ["8.2"] },
  { term: "Equality Act 2010", def: "The UK's discrimination statute, protecting nine characteristics. It never mentions algorithms and does not need to: liability attaches to outcomes, and an AI system producing worse outcomes for a protected group exposes the organisation that deployed it.", source: "UK statute", related: ["3.1"] },
  { term: "Explainability", def: "The capability to state, in plain language, why a system produced this output for this person — main factors, specific to the case, at a level the recipient can act on. Built at procurement or build time; nearly impossible to retrofit.", related: ["4.3", "4.5"] },
  { term: "Four safeguards", def: "The DUAA's requirements for significant automated decisions: the person is informed, can make representations, can obtain human intervention, and can contest the outcome. Each must be operational — a working mechanism with an owner and records, not a paragraph in a policy.", source: "UK GDPR Article 22C", related: ["4.4", "5.2"] },
  { term: "FRC", def: "The Financial Reporting Council: regulator of UK corporate governance and author of the 2024 Code, whose Provision 29 declaration brings AI within the board's material-controls attestation from the 2026 reporting cycle.", source: "UK regulator", related: ["1.1", "6.8"] },
  { term: "FRIA", def: "A Fundamental Rights Impact Assessment: the AI Act's required assessment for high-risk systems deployed by public bodies and by banking or insurance entities in defined uses. Broader than a DPIA — dignity, non-discrimination, redress — and complementary to it, not a substitute.", source: "EU AI Act Article 27", related: ["2.3"] },
  { term: "GHG Protocol", def: "The standard method for corporate greenhouse-gas accounting, dividing emissions into Scopes 1, 2 and 3 with fifteen categories of value-chain emissions. The arithmetic underneath every serious sustainability disclosure.", source: "GHG Protocol", related: ["8.3"] },
  { term: "Hallucination", def: "A generative system producing confident, fluent output that is factually wrong. Tracked as a telemetry rate because it announces itself in metrics long before it announces itself in headlines.", related: ["2.7"] },
  { term: "Horizon scanning", def: "A defined process — watchlist, cadence, change log, named owner — for tracking the regulatory instruments that can change your obligations, and converting movement into action. The alternative is discovering deadlines from headlines, usually late.", source: "Principled Futures framework", related: ["1.6"] },
  { term: "Human intervention", def: "The DUAA safeguard entitling a person to have a human re-take an automated decision. The intervening human must meet the meaningful-involvement standard — competent, reasoning-sighted, authorised to reverse — or the intervention is ceremony.", source: "UK GDPR Article 22C", related: ["3.5", "4.4"] },
  { term: "ICO", def: "The Information Commissioner's Office: the UK's data-protection regulator, with powers including assessment notices and audits. Its guidance defines, among much else, what makes human involvement in automated decisions meaningful.", source: "UK regulator", related: ["3.5"] },
  { term: "IDTA", def: "The UK's International Data Transfer Addendum: the contractual mechanism (alongside the UK Extension to the Data Privacy Framework) that keeps personal-data transfers to other countries lawful.", source: "UK GDPR transfer regime" },
  { term: "Incident clocks", def: "The AI Act's serious-incident reporting deadlines: fifteen days generally, ten where a death is involved, two for widespread infringement or critical-infrastructure disruption. They start at awareness of the causal link — ready or not.", source: "EU AI Act", related: ["2.6", "6.5"] },
  { term: "ISO/IEC 42001", def: "The international management-system standard for AI — the certifiable framework for how an organisation governs its AI estate, explicitly commended in UK guidance. One of the proportionate routes to independent assurance.", source: "International standard", related: ["1.7"] },
  { term: "Kill-switch", def: "The tested ability to stop an AI system quickly: defined triggers, authorised roles, dual authorisation, rollback and a business fallback. A governance control that has to be built and rehearsed, because it cannot be improvised on the day.", source: "Principled Futures framework", related: ["6.4"] },
  { term: "Lawful basis", def: "The legal ground every processing of personal data must rest on — consent, contract, legal obligation, vital interests, public task or legitimate interests. AI deployments typically need a basis per purpose: training, operation and outputs.", source: "UK GDPR Article 6", related: ["5.3"] },
  { term: "Legitimate interests", def: "The most flexible lawful basis: processing necessary for interests not overridden by the individual's rights, evidenced by a documented balancing test. One blanket recital stretched across an AI system's purposes is not an analysis; it is a hope.", source: "UK GDPR Article 6(1)(f)", related: ["5.3"] },
  { term: "Machine-readable marking", def: "The AI Act's requirement that synthetic content carry technical, detectable marking — layered metadata plus watermarking — not merely a visible label. A caption is a label; the duty asks for detectability that survives cropping, compression and paraphrase.", source: "EU AI Act Article 50", related: ["4.2"] },
  { term: "Maturity bands", def: "The five levels of the 0–4 scale: Initial, Developing, Defined, Managed, Leading. Scores of 0–100 map to bands at thresholds of 20, 40, 60 and 80 — the same language across the assessment, telemetry and report.", source: "Principled Futures framework" },
  { term: "Meaningful human involvement", def: "The legal test deciding whether a decision escapes the solely-automated regime: the reviewing human must have the competence to understand the output, access to the system's reasoning, and the authority to override it. Rubber-stamping fails it.", source: "DUAA / ICO guidance", related: ["3.5", "5.1"] },
  { term: "Model card", def: "A structured record of what an AI system is for, what data trained it, how it performs across groups, and where it should not be used. Becoming the lingua franca of fairness and procurement evidence.", related: ["3.3", "4.5"] },
  { term: "Model drift", def: "The gradual divergence between what a model was trained on and the world it now operates in, degrading accuracy silently. One of the core telemetry measures, because drift announces itself in numbers before outcomes.", related: ["2.7"] },
  { term: "NCSC", def: "The UK's National Cyber Security Centre, whose guidelines for secure AI system development set the design bar across the lifecycle — and anchor the government's voluntary Code of Practice for the cyber security of AI.", source: "UK agency", related: ["6.2"] },
  { term: "Omnibus (Digital / Omnibus I)", def: "The EU's 2025–26 simplification packages: the Digital Omnibus adjusted AI Act timelines and SME accommodations; Omnibus I cut CSRD's mandatory scope to 1,000 employees and created the protected-undertaking value-chain cap.", source: "EU legislation", related: ["2.8", "8.1", "8.4"] },
  { term: "Parity band", def: "The practitioner convention for disparate-impact testing: outcome ratios between groups within roughly 0.8 and 1.25 are treated as within tolerance; divergence beyond triggers investigation. The threshold matters less than defining it in advance.", related: ["3.3"] },
  { term: "PECR", def: "The UK's Privacy and Electronic Communications Regulations: the rules on cookies, tracking and electronic marketing. Strictly necessary storage — like this product's local answer storage — needs no consent banner; everything else does.", source: "UK regulations" },
  { term: "Prompt injection", def: "Instructions smuggled into content an AI system processes, hijacking its behaviour from inside the data channel. A category error for perimeter security thinking, because the attack arrives as payload, not intrusion.", source: "NCSC secure AI guidance", related: ["6.1"] },
  { term: "Protected characteristics", def: "The nine grounds the Equality Act protects: age, disability, gender reassignment, marriage and civil partnership, pregnancy and maternity, race, religion or belief, sex, and sexual orientation. The map every AI use should be checked against.", source: "Equality Act 2010", related: ["3.1"] },
  { term: "Protected undertaking", def: "An organisation with fewer than 1,000 employees, which may lawfully refuse value-chain data requests exceeding the voluntary SME standard. A right that protects nobody unless exercised.", source: "Omnibus I Directive", related: ["8.4"] },
  { term: "Provider", def: "The organisation that develops an AI system or has it developed and places it on the market. Providers carry the design-side duties — documentation, marking, energy disclosure — that deployers depend on downstream.", source: "EU AI Act" },
  { term: "Provision 29", def: "The UK Corporate Governance Code 2024 provision requiring boards to declare annually on the effectiveness of material internal controls — a boundary the FRC has said includes IT, cyber and AI. Attestation, not just monitoring, from the 2026 cycle.", source: "UK Corporate Governance Code 2024", related: ["1.1", "6.8"] },
  { term: "Proxy variable", def: "An innocuous-looking data field that statistically reconstructs a protected characteristic — postcode, school, surname, employment gaps. Deleting the labelled column achieves little while the proxies keep discriminating.", related: ["3.2"] },
  { term: "RACI", def: "A decision-rights map: who is Responsible, Accountable, Consulted and Informed for each system. For AI, the accountable name must survive the legal test — could this person genuinely override the system, and would they know when to?", related: ["1.2"] },
  { term: "Recognised legitimate interests", def: "The DUAA's new lawful basis for defined public-interest purposes — with an explicit statutory bar: it cannot ground significant automated decisions. Reaching for it for ADM misreads the Act at the exact point the Act anticipated.", source: "UK GDPR Article 6(1)(ea)", related: ["5.3"] },
  { term: "Red-teaming", def: "Deliberate, authorised attack on your own systems to find what a real adversary would. For AI, the step that turns a threat model from hypothesis into tested control.", related: ["6.1", "1.7"] },
  { term: "Ring (accountability)", def: "One of the three circles of people around the telemetry measures — run it (daily users), steer it (rule-setters), check it (outside eyes) — each with its own review rhythm. Every measure is owned in exactly one ring.", source: "Principled Futures telemetry", related: ["7.2"] },
  { term: "Risk appetite", def: "The board's written statement of which AI uses it embraces, tolerates with controls, or refuses — with tolerances concrete enough to guide a real decision. Unwritten appetite is enforced by luck.", source: "Principled Futures framework", related: ["2.2"] },
  { term: "Risk tiers (AI Act)", def: "The AI Act's four-level classification: prohibited practices, high risk, limited risk (transparency duties), and minimal risk. Obligations attach to tier, and deployment context sets the tier — the same model can sit in different tiers in different uses.", source: "EU AI Act", related: ["2.1"] },
  { term: "s172 (Companies Act)", def: "The director's duty to promote the company's success with regard to stakeholder interests — tested procedurally, through what the minutes show was actually weighed. For AI adoption, the minute book is where the safe harbour is built.", source: "Companies Act 2006", related: ["1.8", "7.4"] },
  { term: "Scope 1, 2 and 3", def: "The GHG Protocol's emission categories: Scope 1 is fuel you burn, Scope 2 is energy you buy, Scope 3 is everything in your value chain — usually estimated, not measured, and respectable when the method is stated.", source: "GHG Protocol", related: ["8.2", "8.3"] },
  { term: "Shadow AI", def: "AI tools staff adopt without approval — personal subscriptions, free tiers, browser extensions — invisible to the register and busy processing whatever was pasted into them. The governed response is a better catalogue and a faster approval route, not a wider ban.", source: "Principled Futures framework", related: ["7.7"] },
  { term: "Significant decision", def: "A decision producing a legal effect on a person or something similarly significant — a job refused, credit declined, an entitlement removed. One of the two tests deciding whether the DUAA's automated-decision regime applies.", source: "UK GDPR Article 22A", related: ["5.1"] },
  { term: "Solely automated", def: "A decision made without meaningful human involvement. The word doing the work is \"meaningful\": a human who forwards what the system decided has not moved the decision out of scope — they have decorated it.", source: "UK GDPR Article 22A", related: ["5.1", "3.5"] },
  { term: "Special-category data", def: "The most sensitive personal data: health, race, religion, sexual orientation, biometrics and their kin. Significant automated decisions based on it remain prohibited by default — and it enters pipelines through side doors like inference and bundled vendor features.", source: "UK GDPR Article 9", related: ["3.4", "5.5"] },
  { term: "Subject access request", def: "A person's right to a copy of their personal data and information about how it is used. Where AI is involved, a complete response includes the algorithmic chapter — the decision-relevant information the safeguards regime already requires.", source: "UK GDPR Article 15", related: ["5.7"] },
  { term: "Telemetry", def: "Continuous measurement of governance health: eleven measures with thresholds, owners and cadences, replacing point-in-time audits with a live register. The bridge from governed-on-paper to governed-in-fact.", source: "Principled Futures", related: ["2.7"] },
  { term: "Threshold", def: "The pre-agreed line that turns a metric reading into a status — within, watch, or breach — and a breach into an escalation. Set from the board's risk appetite, not discovered after the fact.", source: "Principled Futures telemetry", related: ["2.2"] },
  { term: "Transparency paradox", def: "The structural bind in which deployers are legally responsible for explanations that their vendors' opaque models make impossible to give. Resolved at procurement — documentation and reasoning access as conditions of purchase — or not at all.", related: ["4.5"] },
  { term: "Twin Transition", def: "The EU's framing that digital and green transformation should advance together rather than trade off. For AI: adopt deliberately, count the energy cost, and let efficiency weigh in vendor choices.", source: "EU policy", related: ["8.5"] },
  { term: "UK Corporate Governance Code 2024", def: "The FRC's governance code for listed companies, applying from 2025 with the Provision 29 material-controls declaration from the 2026 reporting cycle. The instrument that moved AI oversight from good practice to board attestation.", source: "FRC", related: ["1.1"] },
  { term: "Value chain", def: "Everyone upstream and downstream of a company's operations — suppliers included. Large companies' sustainability duties reach their value chains, which is how reporting obligations arrive at SMEs by contract rather than statute.", source: "CSRD", related: ["8.1"] },
  { term: "VSME", def: "The Voluntary Sustainability Reporting Standard for SMEs, published by EFRAG: a Basic Module (B1–B11) and a Comprehensive Module (C1–C9). The standardised answer to the questionnaire flood — produced once, reused everywhere.", source: "EFRAG", related: ["8.2", "8.3"] },
  { term: "Watermarking", def: "Embedding robust, machine-detectable signals in AI-generated content so it can be identified as synthetic even after editing. One layer of the AI Act's marking architecture, alongside secured metadata — with legacy systems' deadline on 2 December 2026.", source: "EU AI Act Article 50", related: ["4.2"] },
];

/** Alphabetical, grouped by first letter, for the glossary page. */
export function glossaryGroups(): { letter: string; entries: GlossaryEntry[] }[] {
  const sorted = [...GLOSSARY].sort((a, b) => a.term.localeCompare(b.term, "en"));
  const groups: { letter: string; entries: GlossaryEntry[] }[] = [];
  for (const e of sorted) {
    const letter = e.term[0].toUpperCase();
    const g = groups[groups.length - 1];
    if (g && g.letter === letter) g.entries.push(e);
    else groups.push({ letter, entries: [e] });
  }
  return groups;
}
