// scripts/seed-content.mjs
// Generates supabase/migrations/0005_seed_content.sql from the real content
// files, so the database copy is always byte-identical to the source of truth
// and nothing is transcribed by hand.
//
//   node scripts/seed-content.mjs
//
// Run this again whenever briefing/glossary/guide copy changes, then apply the
// migration. The generated file is idempotent (upserts on primary key), so
// re-running it updates rather than duplicates.

import { readFile, writeFile, mkdir, rm } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const tmp = path.join(root, ".seed-tmp");

// Free samples: the opening criterion of each domain. This is the shop window
// for signed-in free accounts — change this list to widen or narrow it.
const SAMPLES = new Set(["1.1", "2.1", "3.1", "4.1", "5.1", "6.1", "7.1", "8.1"]);

/**
 * Pull one exported array literal out of a .ts file and evaluate it.
 * We slice out just the literal rather than transpiling the module, because
 * these files also export helper functions whose type annotations plain Node
 * cannot parse. The literal itself is pure data, so it evaluates as-is —
 * escapes, accents and guillemets all survive verbatim.
 */
async function loadTs(relPath, exportName) {
  const src = await readFile(path.join(root, relPath), "utf8");
  const re = new RegExp(`export const ${exportName}[^=]*=\\s*(\\[[\\s\\S]*?\\n\\];)`);
  const m = src.match(re);
  if (!m) throw new Error(`${relPath}: could not find "export const ${exportName} = [ ... ];"`);
  const literal = m[1].replace(/;\s*$/, "");
  const val = new Function(`return ${literal}`)();
  if (!Array.isArray(val)) throw new Error(`${relPath}: ${exportName} is not an array`);
  return val;
}

const q = (s) => `'${String(s).replace(/'/g, "''")}'`;
const jsonb = (v) => `${q(JSON.stringify(v))}::jsonb`;

const articles = await loadTs("src/lib/articles.ts", "ARTICLES");
const glossary = await loadTs("src/lib/glossary.ts", "GLOSSARY");
const guides = await loadTs("src/lib/guides.ts", "GUIDES");

const lines = [];
lines.push(`-- 0005_seed_content.sql`);
lines.push(`-- GENERATED by scripts/seed-content.mjs — do not edit by hand.`);
lines.push(`-- Source of truth remains src/lib/{articles,glossary,guides}.ts.`);
lines.push(`-- ${articles.length} briefings, ${glossary.length} glossary terms, ${guides.length} guides.`);
lines.push("");

lines.push(`-- Briefings ---------------------------------------------------------------`);
for (const a of articles) {
  lines.push(
    `insert into briefings (criterion_id, body, is_sample) values (${q(a.id)}, ${jsonb(a.body)}, ${SAMPLES.has(a.id)})\n` +
    `  on conflict (criterion_id) do update set body = excluded.body, is_sample = excluded.is_sample, updated_at = now();`,
  );
}
lines.push("");

lines.push(`-- Glossary ----------------------------------------------------------------`);
for (const g of glossary) {
  lines.push(
    `insert into glossary_terms (term, def) values (${q(g.term)}, ${q(g.def)})\n` +
    `  on conflict (term) do update set def = excluded.def, updated_at = now();`,
  );
}
lines.push("");

lines.push(`-- Guides ------------------------------------------------------------------`);
for (const g of guides) {
  lines.push(
    `insert into guides (id, body) values (${q(g.id)}, ${jsonb(g.body)})\n` +
    `  on conflict (id) do update set body = excluded.body, updated_at = now();`,
  );
}
lines.push("");

const dest = path.join(root, "supabase/migrations/0005_seed_content.sql");
await writeFile(dest, lines.join("\n"), "utf8");
await rm(tmp, { recursive: true, force: true });

// ---------------------------------------------------------------------------
// The client-side metadata module.
//
// This is what the app imports. It carries everything needed to browse, link
// and search the library — titles, categories, reading times, standfirsts —
// but no body prose and no glossary definitions. Those come from the database
// at read time, checked against the caller's plan.
//
// src/lib/{articles,glossary,guides}.ts stay put as the source of truth and
// are read only by this script, at build time. Nothing in the app imports
// them, and scripts/check-bundle.mjs fails the build if that ever changes.
// ---------------------------------------------------------------------------
const meta = [];
meta.push(`// src/lib/content-meta.ts`);
meta.push(`// GENERATED by scripts/seed-content.mjs — do not edit by hand.`);
meta.push(`// Metadata only: titles, categories, standfirsts. Body prose and glossary`);
meta.push(`// definitions live in the database (see supabase/migrations/0004_content_tables.sql)`);
meta.push(`// and are fetched per-user by src/lib/content.ts.`);
meta.push("");
meta.push(`export interface ArticleMeta { id: string; title: string; category: string; read: string; extract: string; isSample: boolean }`);
meta.push(`export interface GlossaryMeta { term: string; source?: string; related?: string[] }`);
meta.push(`export interface GuideMeta { id: string; title: string }`);
meta.push("");
meta.push(`export const ARTICLE_META: ArticleMeta[] = ${JSON.stringify(
  articles.map((a) => ({ id: a.id, title: a.title, category: a.category, read: a.read, extract: a.extract, isSample: SAMPLES.has(a.id) })),
  null, 2,
)};`);
meta.push("");
meta.push(`export const GLOSSARY_META: GlossaryMeta[] = ${JSON.stringify(
  glossary.map((g) => ({ term: g.term, ...(g.source ? { source: g.source } : {}), ...(g.related ? { related: g.related } : {}) })),
  null, 2,
)};`);
meta.push("");
meta.push(`export const GUIDE_META: GuideMeta[] = ${JSON.stringify(
  guides.map((g) => ({ id: g.id, title: g.title })), null, 2,
)};`);
meta.push("");
meta.push(`/** Briefing metadata for a criterion id, or undefined if none exists. */`);
meta.push(`export function articleFor(criterionId: string): ArticleMeta | undefined {`);
meta.push(`  return ARTICLE_META.find((a) => a.id === criterionId);`);
meta.push(`}`);
meta.push("");
meta.push(`/** Glossary terms grouped by initial letter, for the A–Z index. */`);
meta.push(`export function glossaryGroups(): { letter: string; entries: GlossaryMeta[] }[] {`);
meta.push(`  const map = new Map<string, GlossaryMeta[]>();`);
meta.push(`  for (const e of GLOSSARY_META) {`);
meta.push(`    const letter = e.term[0].toUpperCase();`);
meta.push(`    const key = /[A-Z]/.test(letter) ? letter : "#";`);
meta.push(`    if (!map.has(key)) map.set(key, []);`);
meta.push(`    map.get(key)!.push(e);`);
meta.push(`  }`);
meta.push(`  return [...map.entries()].sort((a, b) => a[0].localeCompare(b[0])).map(([letter, entries]) => ({ letter, entries }));`);
meta.push(`}`);
meta.push("");

const metaDest = path.join(root, "src/lib/content-meta.ts");
await writeFile(metaDest, meta.join("\n"), "utf8");

const words = articles.reduce((n, a) => n + a.body.join(" ").split(/\s+/).length, 0);
console.log(`Wrote ${path.relative(root, dest)}`);
console.log(`  ${articles.length} briefings (${SAMPLES.size} free samples, ${words.toLocaleString()} words)`);
console.log(`  ${glossary.length} glossary terms`);
console.log(`  ${guides.length} guides`);
console.log(`Wrote src/lib/content-meta.ts (metadata only — no body prose)`);
