// scripts/seed-content.mjs
// Generates supabase/migrations/0005_seed_content.sql from the real content
// files, so the database copy is always byte-identical to the source of truth
// and nothing is transcribed by hand.
//
//   node scripts/seed-content.mjs
//
// Run this again whenever briefing/glossary/guide copy changes, then apply the
// migration. The generated file is idempotent (upserts on primary key), so
// re-running it updates rather than duplicates.

import { readFile, writeFile, mkdir, rm } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const tmp = path.join(root, ".seed-tmp");

// Free samples: the opening criterion of each domain. This is the shop window
// for signed-in free accounts — change this list to widen or narrow it.
const SAMPLES = new Set(["1.1", "2.1", "3.1", "4.1", "5.1", "6.1", "7.1", "8.1"]);

/**
 * Pull one exported array literal out of a .ts file and evaluate it.
 * We slice out just the literal rather than transpiling the module, because
 * these files also export helper functions whose type annotations plain Node
 * cannot parse. The literal itself is pure data, so it evaluates as-is —
 * escapes, accents and guillemets all survive verbatim.
 */
async function loadTs(relPath, exportName) {
  const src = await readFile(path.join(root, relPath), "utf8");
  const re = new RegExp(`export const ${exportName}[^=]*=\\s*(\\[[\\s\\S]*?\\n\\];)`);
  const m = src.match(re);
  if (!m) throw new Error(`${relPath}: could not find "export const ${exportName} = [ ... ];"`);
  const literal = m[1].replace(/;\s*$/, "");
  const val = new Function(`return ${literal}`)();
  if (!Array.isArray(val)) throw new Error(`${relPath}: ${exportName} is not an array`);
  return val;
}

const q = (s) => `'${String(s).replace(/'/g, "''")}'`;
const jsonb = (v) => `${q(JSON.stringify(v))}::jsonb`;

const legacyArticles = await loadTs("src/lib/articles.ts", "ARTICLES");
const frameworkSrc = await readFile(path.join(root, "src/lib/framework.ts"), "utf8");

/**
 * An approved evidence brief replaces the legacy briefing for its criterion:
 * new body, new title (the criterion's own), a reading list and a checked
 * date. Drafts are ignored, so nothing unapproved can reach the product.
 */
async function approvedBrief(id) {
  let md, lib;
  try {
    md = await readFile(path.join(root, `content/briefs/1.0.0/${id}.md`), "utf8");
    lib = JSON.parse(await readFile(path.join(root, `content/library/1.0.0/${id}.json`), "utf8"));
  } catch { return null; }
  const fm = md.match(/^---\n([\s\S]*?)\n---/);
  if (!fm || !/^status:\s*approved\s*$/m.test(fm[1]) || lib.status !== "approved") return null;
  const checked = (fm[1].match(/^checked:\s*(\S+)/m) || [])[1] || null;
  const rest = md.slice(fm[0].length);
  const title = (rest.match(/^# (.+)$/m) || [])[1].trim();
  const paras = rest.replace(/^# .+$/m, "").split(/\n\s*\n/).map((x) => x.trim()).filter(Boolean);
  const measures = paras[0].replace(/^\*\*[^*]+\*\*\s*/, "");
  const words = paras.join(" ").split(/\s+/).length;
  const sources = lib.items.map(({ title, publisher, year, url, locator, access }) => ({ title, publisher, year, url, locator, access }));
  return { title, body: paras, extract: measures, read: `${Math.max(1, Math.round(words / 200))} min`, sources, checked };
}

const articles = [];
let replaced = 0;
for (const a of legacyArticles) {
  const b = await approvedBrief(a.id);
  if (b) { replaced++; articles.push({ ...a, ...b, evidence: true }); }
  else articles.push({ ...a, sources: [], checked: null, evidence: false });
}
void frameworkSrc;
const glossary = await loadTs("src/lib/glossary.ts", "GLOSSARY");
const guides = await loadTs("src/lib/guides.ts", "GUIDES");

const lines = [];
lines.push(`-- 0005_seed_content.sql`);
lines.push(`-- GENERATED by scripts/seed-content.mjs — do not edit by hand.`);
lines.push(`-- Source of truth remains src/lib/{articles,glossary,guides}.ts.`);
lines.push(`-- ${articles.length} briefings, ${glossary.length} glossary terms, ${guides.length} guides.`);
lines.push("");

lines.push(`-- Briefings ---------------------------------------------------------------`);
for (const a of articles) {
  lines.push(
    `insert into briefings (criterion_id, body, is_sample, sources, checked) values (${q(a.id)}, ${jsonb(a.body)}, ${SAMPLES.has(a.id)}, ${jsonb(a.sources)}, ${a.checked ? q(a.checked) : "null"})\n` +
    `  on conflict (criterion_id) do update set body = excluded.body, is_sample = excluded.is_sample, sources = excluded.sources, checked = excluded.checked, updated_at = now();`,
  );
}
lines.push("");

lines.push(`-- Glossary ----------------------------------------------------------------`);
for (const g of glossary) {
  lines.push(
    `insert into glossary_terms (term, def) values (${q(g.term)}, ${q(g.def)})\n` +
    `  on conflict (term) do update set def = excluded.def, updated_at = now();`,
  );
}
lines.push("");

lines.push(`-- Guides ------------------------------------------------------------------`);
for (const g of guides) {
  lines.push(
    `insert into guides (id, body) values (${q(g.id)}, ${jsonb(g.body)})\n` +
    `  on conflict (id) do update set body = excluded.body, updated_at = now();`,
  );
}
lines.push("");

const dest = path.join(root, "supabase/migrations/0005_seed_content.sql");
await writeFile(dest, lines.join("\n"), "utf8");
await rm(tmp, { recursive: true, force: true });

// ---------------------------------------------------------------------------
// The client-side metadata module.
//
// This is what the app imports. It carries everything needed to browse, link
// and search the library — titles, categories, reading times, standfirsts —
// but no body prose and no glossary definitions. Those come from the database
// at read time, checked against the caller's plan.
//
// src/lib/{articles,glossary,guides}.ts stay put as the source of truth and
// are read only by this script, at build time. Nothing in the app imports
// them, and scripts/check-bundle.mjs fails the build if that ever changes.
// ---------------------------------------------------------------------------
const meta = [];
meta.push(`// src/lib/content-meta.ts`);
meta.push(`// GENERATED by scripts/seed-content.mjs — do not edit by hand.`);
meta.push(`// Metadata only: titles, categories, standfirsts. Body prose and glossary`);
meta.push(`// definitions live in the database (see supabase/migrations/0004_content_tables.sql)`);
meta.push(`// and are fetched per-user by src/lib/content.ts.`);
meta.push("");
meta.push(`export interface ArticleMeta { id: string; title: string; category: string; read: string; extract: string; isSample: boolean; evidence: boolean }`);
meta.push(`export interface GlossaryMeta { term: string; source?: string; related?: string[] }`);
meta.push(`export interface GuideMeta { id: string; title: string }`);
meta.push("");
meta.push(`export const ARTICLE_META: ArticleMeta[] = ${JSON.stringify(
  articles.map((a) => ({ id: a.id, title: a.title, category: a.category, read: a.read, extract: a.extract, isSample: SAMPLES.has(a.id), evidence: a.evidence })),
  null, 2,
)};`);
meta.push("");
meta.push(`export const GLOSSARY_META: GlossaryMeta[] = ${JSON.stringify(
  glossary.map((g) => ({ term: g.term, ...(g.source ? { source: g.source } : {}), ...(g.related ? { related: g.related } : {}) })),
  null, 2,
)};`);
meta.push("");
meta.push(`export const GUIDE_META: GuideMeta[] = ${JSON.stringify(
  guides.map((g) => ({ id: g.id, title: g.title })), null, 2,
)};`);
meta.push("");
// Library statistics for the landing page: counts only, drawn from the reading lists, so the public
// figures can never drift from what the product actually holds.
{
  const { readdir } = await import("node:fs/promises");
  const dir = path.join(root, "content/library/1.0.0");
  const docs = new Map(); let citations = 0;
  for (const f of (await readdir(dir)).filter((n) => n.endsWith(".json"))) {
    const lib = JSON.parse(await readFile(path.join(dir, f), "utf8"));
    for (const it of lib.items) { citations++; const k = it.url.split("#")[0].replace(/\/$/, ""); if (!docs.has(k)) docs.set(k, it); }
  }
  const byType = {}; const byJurisdiction = {};
  for (const it of docs.values()) {
    byType[it.type || "other"] = (byType[it.type || "other"] || 0) + 1;
    byJurisdiction[it.jurisdiction || "other"] = (byJurisdiction[it.jurisdiction || "other"] || 0) + 1;
  }
  // How many exact passages (quotations and figures) the daily check re-reads. A count only: the
  // passages themselves are paid content and must never reach the bundle.
  let anchors = 0;
  try {
    const a = JSON.parse(await readFile(path.join(root, "content/sources/anchors.json"), "utf8"));
    for (const [k, v] of Object.entries(a)) if (!k.startsWith("_")) anchors += v.length;
  } catch { /* no anchors file */ }
  meta.push(`export const LIBRARY_STATS = ${JSON.stringify({ documents: docs.size, citations, anchors, byType, byJurisdiction }, null, 2)} as const;`);

  // Links between criteria, for the landing-page map: two criteria are joined when their reading lists
  // rest on the same documents. A factual signal from the research (ids and a count only, no wording),
  // not a judgement about tension or dependency: typed links are a later, founder-approved stage.
  const uses = new Map();
  for (const f of (await readdir(dir)).filter((n) => n.endsWith(".json"))) {
    const id = f.replace(/\.json$/, "");
    const lib = JSON.parse(await readFile(path.join(dir, f), "utf8"));
    for (const it of lib.items) {
      const k = it.url.split("#")[0].replace(/\/$/, "");
      if (!uses.has(k)) uses.set(k, new Set());
      uses.get(k).add(id);
    }
  }
  const pair = new Map();
  for (const ids of uses.values()) {
    const list = [...ids].sort();
    if (list.length > 12) continue; // a document nearly every criterion cites says nothing about a pair
    for (let i = 0; i < list.length; i++) for (let j = i + 1; j < list.length; j++) {
      const key = `${list[i]}|${list[j]}`; pair.set(key, (pair.get(key) || 0) + 1);
    }
  }
  const ranked = [...pair.entries()].map(([k, w]) => { const [a, b] = k.split("|"); return { a, b, w }; })
    .sort((x, y) => y.w - x.w || x.a.localeCompare(y.a) || x.b.localeCompare(y.b));
  const degree = {}; const chosen = [];
  const take = (l) => { chosen.push(l); degree[l.a] = (degree[l.a] || 0) + 1; degree[l.b] = (degree[l.b] || 0) + 1; };
  for (const l of ranked) if (l.w >= 2 && chosen.length < 120 && (degree[l.a] || 0) < 7 && (degree[l.b] || 0) < 7) take(l);
  for (const l of ranked) if (chosen.length < 150 && !chosen.includes(l) && ((degree[l.a] || 0) < 2 || (degree[l.b] || 0) < 2)) take(l);
  meta.push(`/** Criteria joined by shared sources: [from, to, documents in common]. */`);
  meta.push(`export const CRITERION_LINKS: [string, string, number][] = ${JSON.stringify(chosen.map((l) => [l.a, l.b, l.w]))};`);
  meta.push("");
  meta.push("");
}
meta.push(`/** Briefing metadata for a criterion id, or undefined if none exists. */`);
meta.push(`export function articleFor(criterionId: string): ArticleMeta | undefined {`);
meta.push(`  return ARTICLE_META.find((a) => a.id === criterionId);`);
meta.push(`}`);
meta.push("");
meta.push(`/** Glossary terms grouped by initial letter, for the A–Z index. */`);
meta.push(`export function glossaryGroups(): { letter: string; entries: GlossaryMeta[] }[] {`);
meta.push(`  const map = new Map<string, GlossaryMeta[]>();`);
meta.push(`  for (const e of GLOSSARY_META) {`);
meta.push(`    const letter = e.term[0].toUpperCase();`);
meta.push(`    const key = /[A-Z]/.test(letter) ? letter : "#";`);
meta.push(`    if (!map.has(key)) map.set(key, []);`);
meta.push(`    map.get(key)!.push(e);`);
meta.push(`  }`);
meta.push(`  return [...map.entries()].sort((a, b) => a[0].localeCompare(b[0])).map(([letter, entries]) => ({ letter, entries }));`);
meta.push(`}`);
meta.push("");

const metaDest = path.join(root, "src/lib/content-meta.ts");
await writeFile(metaDest, meta.join("\n"), "utf8");

const words = articles.reduce((n, a) => n + a.body.join(" ").split(/\s+/).length, 0);
console.log(`Wrote ${path.relative(root, dest)}`);
console.log(`  ${articles.length} briefings (${SAMPLES.size} free samples, ${words.toLocaleString()} words)`);
console.log(`  ${replaced} of ${articles.length} are approved evidence briefs; the rest are legacy briefings`);
console.log(`  ${glossary.length} glossary terms`);
console.log(`  ${guides.length} guides`);
console.log(`Wrote src/lib/content-meta.ts (metadata only — no body prose)`);
